import { ok, fail, type EngineResult } from '@/src/types/engineResult';
import type {
  OperationalItem,
  OperationalItemDraft,
  OperationalItemPatch,
  OperationalItemStatus,
  OperationalItemStatusChange,
} from '@/src/types/operationalItem';

const allowedTransitions: Record<OperationalItemStatus, OperationalItemStatus[]> = {
  draft: ['triaged', 'cancelled'],
  triaged: ['a_fazer', 'ready', 'cancelled'],
  a_fazer: ['ready', 'inProgress', 'cancelled'],
  ready: ['inProgress', 'cancelled'],
  inProgress: ['awaitingEvidence', 'em_validacao', 'completed', 'vencido', 'cancelled'],
  awaitingEvidence: ['inProgress', 'em_validacao', 'vencido', 'cancelled'],
  em_validacao: ['inProgress', 'completed', 'cancelled'],
  vencido: ['inProgress', 'awaitingEvidence', 'em_validacao', 'cancelled'],
  completed: ['inProgress'],
  cancelled: [],
};

function nowIso(): string {
  return new Date().toISOString();
}

function buildHistoryEvent(
  fromStatus: OperationalItemStatus | undefined,
  toStatus: OperationalItemStatus,
  note?: string,
  changedBy?: string
): OperationalItemStatusChange {
  return {
    fromStatus,
    toStatus,
    changedAt: nowIso(),
    changedBy,
    note,
  };
}

export function validateOperationalItem(item: OperationalItemDraft): string[] {
  const errors: string[] = [];
  if (!item.title?.trim()) errors.push('Item operacional precisa de titulo.');
  if (!item.kind) errors.push('Item operacional precisa de classificacao.');
  if (!item.priority) errors.push('Item operacional precisa de prioridade.');
  if (!item.status) errors.push('Item operacional precisa de status.');
  if (!item.sourceLinks || item.sourceLinks.length === 0) {
    errors.push('Item operacional precisa manter ao menos uma origem rastreavel.');
  }
  return errors;
}

export function createOperationalItem(
  draft: OperationalItemDraft,
  actor?: string
): EngineResult<OperationalItem> {
  const errors = validateOperationalItem(draft);
  if (errors.length > 0) {
    return fail(errors, {
      id: draft.id ?? 'invalid-item',
      title: draft.title ?? '',
      kind: draft.kind ?? 'observation',
      priority: draft.priority ?? 'baixa',
      status: draft.status ?? 'draft',
      nrIds: draft.nrIds ?? [],
      sourceLinks: draft.sourceLinks ?? [],
      ruleLinks: draft.ruleLinks ?? [],
      blocking: draft.blocking ?? false,
      evidencePlan: draft.evidencePlan ?? {
        required: false,
        minimumCount: 0,
        acceptedKinds: [],
        blockingForCompletion: false,
        rationale: [],
      },
      evidenceIds: draft.evidenceIds ?? [],
      history: draft.history ?? [],
      createdAt: draft.createdAt ?? nowIso(),
      updatedAt: draft.updatedAt ?? nowIso(),
    });
  }

  const item: OperationalItem = {
    id: draft.id ?? globalThis.crypto.randomUUID(),
    title: draft.title,
    description: draft.description,
    kind: draft.kind,
    priority: draft.priority,
    status: draft.status,
    sector: draft.sector,
    contextId: draft.contextId,
    activityId: draft.activityId,
    checklistId: draft.checklistId,
    inspectionId: draft.inspectionId,
    fieldInputId: draft.fieldInputId,
    nrIds: draft.nrIds,
    sourceLinks: draft.sourceLinks,
    ruleLinks: draft.ruleLinks,
    blocking: draft.blocking,
    responsible: draft.responsible,
    responsibleRole: draft.responsibleRole,
    dueAt: draft.dueAt,
    evidencePlan: draft.evidencePlan,
    evidenceIds: draft.evidenceIds,
    requiredDocuments: draft.requiredDocuments,
    recommendedActions: draft.recommendedActions,
    tags: draft.tags,
    detectedKeywords: draft.detectedKeywords,
    autoGenerated: draft.autoGenerated,
    legacyReferences: draft.legacyReferences,
    history:
      draft.history && draft.history.length > 0
        ? draft.history
        : [buildHistoryEvent(undefined, draft.status, 'Criacao do item operacional.', actor)],
    createdAt: draft.createdAt ?? nowIso(),
    createdBy: draft.createdBy ?? actor,
    updatedAt: draft.updatedAt ?? nowIso(),
  };

  return ok(item);
}

export function updateOperationalItem(
  current: OperationalItem,
  patch: OperationalItemPatch
): EngineResult<OperationalItem> {
  const updated: OperationalItem = {
    ...current,
    ...patch,
    id: current.id,
    history: current.history,
    updatedAt: nowIso(),
  };

  const errors = validateOperationalItem(updated);
  if (errors.length > 0) return fail(errors, updated);

  return ok(updated);
}

export function transitionOperationalItem(
  current: OperationalItem,
  nextStatus: OperationalItemStatus,
  actor?: string,
  note?: string
): EngineResult<OperationalItem> {
  if (current.status === nextStatus) {
    return ok(current, ['Item operacional ja estava no status solicitado.']);
  }

  const allowed = allowedTransitions[current.status] ?? [];
  if (!allowed.includes(nextStatus)) {
    return fail(
      [`Transicao invalida: ${current.status} -> ${nextStatus}.`],
      current
    );
  }

  const warnings: string[] = [];
  if (
    nextStatus === 'completed' &&
    current.evidencePlan.required &&
    current.evidenceIds.length < current.evidencePlan.minimumCount
  ) {
    warnings.push('Conclusao sem evidencia suficiente deve ser revalidada pelo evidenceEngine.');
  }

  const transitioned: OperationalItem = {
    ...current,
    status: nextStatus,
    updatedAt: nowIso(),
    history: [...current.history, buildHistoryEvent(current.status, nextStatus, note, actor)],
  };

  return ok(transitioned, warnings);
}

export const operationalItemEngine = {
  validate: validateOperationalItem,
  create: createOperationalItem,
  update: updateOperationalItem,
  transition: transitionOperationalItem,
};
