import type { CriticalActivity } from '@/src/types/criticalActivity';

export const CRITICAL_ACTIVITIES: CriticalActivity[] = [
  {
    id: 'trabalho-altura',
    name: 'Trabalho em altura',
    keywords: ['altura', 'telhado', 'andaime', 'escada', 'fachada'],
    relatedNrs: ['NR-35'],
    baseSeverity: 'critica',
    requiredPpe: ['cinto paraquedista', 'talabarte', 'linha de vida'],
    requiredDocuments: ['APR', 'PT', 'treinamento NR-35', 'plano de resgate'],
    requiredEvidenceKinds: ['photo', 'document'],
    contextIds: ['trabalho-altura'],
    blocksOperationOnNonConformity: true,
    active: true,
  },
  {
    id: 'manutencao-eletrica',
    name: 'Manutencao eletrica',
    keywords: ['eletricidade', 'painel', 'energizado', 'loto', 'desenergizacao'],
    relatedNrs: ['NR-10'],
    baseSeverity: 'critica',
    requiredPpe: ['luva isolante', 'protecao facial', 'ferramenta isolada'],
    requiredDocuments: ['APR', 'PT', 'prontuario eletrico', 'treinamento NR-10'],
    requiredEvidenceKinds: ['photo', 'document'],
    contextIds: ['subestacao-eletrica', 'oficina-manutencao'],
    blocksOperationOnNonConformity: true,
    active: true,
  },
  {
    id: 'operacao-maquinas',
    name: 'Operacao de maquinas',
    keywords: ['maquina', 'prensa', 'serra', 'torno', 'equipamento'],
    relatedNrs: ['NR-12'],
    baseSeverity: 'alta',
    requiredPpe: ['oculos', 'protecao auditiva', 'bloqueio'],
    requiredDocuments: ['procedimento', 'analise de risco'],
    requiredEvidenceKinds: ['photo'],
    contextIds: ['linha-producao', 'oficina-manutencao'],
    blocksOperationOnNonConformity: true,
    active: true,
  },
  {
    id: 'espaco-confinado',
    name: 'Espaco confinado',
    keywords: ['espaco confinado', 'tanque', 'silo', 'galeria', 'poço', 'poco'],
    relatedNrs: ['NR-33'],
    baseSeverity: 'critica',
    requiredPpe: ['detector de gases', 'tripé', 'ventilacao'],
    requiredDocuments: ['PET', 'APR', 'plano de resgate', 'treinamento NR-33'],
    requiredEvidenceKinds: ['photo', 'document'],
    contextIds: ['espaco-confinado'],
    blocksOperationOnNonConformity: true,
    active: true,
  },
  {
    id: 'trabalho-quente',
    name: 'Trabalho a quente',
    keywords: ['solda', 'oxicorte', 'maçarico', 'macarico', 'faísca', 'faisca'],
    relatedNrs: ['NR-18', 'NR-20', 'NR-34'],
    baseSeverity: 'alta',
    requiredPpe: ['mascara de solda', 'avental', 'luvas'],
    requiredDocuments: ['PT', 'APR'],
    requiredEvidenceKinds: ['photo'],
    contextIds: ['oficina-manutencao', 'patio-carga'],
    blocksOperationOnNonConformity: true,
    active: true,
  },
  {
    id: 'movimentacao-cargas',
    name: 'Movimentacao de cargas',
    keywords: ['carga', 'guindaste', 'ponte rolante', 'empilhadeira', 'içamento', 'icamento'],
    relatedNrs: ['NR-11'],
    baseSeverity: 'alta',
    requiredPpe: ['capacete', 'botina', 'colete'],
    requiredDocuments: ['plano de içamento', 'APR'],
    requiredEvidenceKinds: ['photo'],
    contextIds: ['almoxarifado-logistico', 'patio-carga'],
    blocksOperationOnNonConformity: true,
    active: true,
  },
];

export function getCriticalActivityById(activityId: string): CriticalActivity | undefined {
  return CRITICAL_ACTIVITIES.find((activity) => activity.id === activityId);
}
