export type NRStatus = 'vigente' | 'revogada';
export type NRCategory = 'geral' | 'especial' | 'setorial' | 'penalidade' | 'revogada';

export type OperationalContextCatalogId =
  | 'base_sst'
  | 'manutencao'
  | 'construcao'
  | 'logistica'
  | 'facilities'
  | 'industria'
  | 'porto'
  | 'saude'
  | 'rural';

export type CriticalActivityCatalogId =
  | 'altura'
  | 'eletricidade'
  | 'maquinas'
  | 'espaco_confinado'
  | 'incendio'
  | 'ergonomia'
  | 'movimentacao_cargas'
  | 'produtos_quimicos';

export interface NRCatalogEntry {
  id: string;
  title: string;
  status: NRStatus;
  category: NRCategory;
  package: string;
  relatedContexts: OperationalContextCatalogId[];
  relatedCriticalActivities: CriticalActivityCatalogId[];
  operationalUse: string;
  penaltyUse: string;
  note: string;
  active: boolean;
}

export const OPERATIONAL_CONTEXT_CATALOG: Array<{
  id: OperationalContextCatalogId;
  title: string;
  note: string;
}> = [
  { id: 'base_sst', title: 'Base SST', note: 'Governanca, rotina, rastreabilidade e disciplina operacional de SST.' },
  { id: 'manutencao', title: 'Manutencao', note: 'Intervencoes tecnicas, energia perigosa, reparos e liberacoes.' },
  { id: 'construcao', title: 'Construcao', note: 'Obras, frentes temporarias, escavacoes, andaimes e isolamento.' },
  { id: 'logistica', title: 'Logistica', note: 'Movimentacao interna, armazenagem, carga e descarga.' },
  { id: 'facilities', title: 'Facilities', note: 'Infraestrutura, predial, utilidades, limpeza e suporte operacional.' },
  { id: 'industria', title: 'Industria', note: 'Processos industriais, maquinas, linhas, manutencao e seguranca de processo.' },
  { id: 'porto', title: 'Porto', note: 'Operacoes portuarias e interfaces de carga, descarga e apoio.' },
  { id: 'saude', title: 'Saude', note: 'Ambientes assistenciais, exposicao biologica e operacao em servicos de saude.' },
  { id: 'rural', title: 'Rural', note: 'Agricultura, pecuaria, silvicultura, exploracao florestal e aquicultura.' },
];

export const CRITICAL_ACTIVITY_CATALOG: Array<{
  id: CriticalActivityCatalogId;
  title: string;
  note: string;
}> = [
  { id: 'altura', title: 'Altura', note: 'Qualquer execucao com potencial de queda em nivel elevado.' },
  { id: 'eletricidade', title: 'Eletricidade', note: 'Intervencao em instalacoes, servicos ou sistemas eletricos.' },
  { id: 'maquinas', title: 'Maquinas', note: 'Operacao, ajuste, setup, limpeza ou manutencao de maquinas.' },
  { id: 'espaco_confinado', title: 'Espaco confinado', note: 'Entrada, permanencia ou resgate em ambiente confinado.' },
  { id: 'incendio', title: 'Incendio', note: 'Resposta, prevencao, isolamento e meios de combate a incendio.' },
  { id: 'ergonomia', title: 'Ergonomia', note: 'Organizacao e desenho do trabalho com risco ergonomico relevante.' },
  { id: 'movimentacao_cargas', title: 'Movimentacao de cargas', note: 'Icamento, transporte, armazenagem e fluxo de materiais.' },
  { id: 'produtos_quimicos', title: 'Produtos quimicos', note: 'Uso, manuseio, armazenamento ou exposicao a agentes quimicos.' },
];

const NR_SOURCE_NOTE =
  'Base oficial conferida no portal do Ministerio do Trabalho e Emprego em 11/05/2026. NR-02 e NR-27 marcadas como revogadas; NR-28 tratada como referencia futura de fiscalizacao e penalidade.';

export const NR_CATALOG: NRCatalogEntry[] = [
  {
    id: 'NR-01',
    title: 'Disposicoes Gerais e Gerenciamento de Riscos Ocupacionais',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'industria', 'construcao', 'logistica', 'facilities', 'porto', 'saude', 'rural', 'manutencao'],
    relatedCriticalActivities: ['altura', 'eletricidade', 'maquinas', 'espaco_confinado', 'incendio', 'ergonomia', 'movimentacao_cargas', 'produtos_quimicos'],
    operationalUse: 'Base de governanca do motor para triagem, prioridade, rastreabilidade e disciplina minima de tratamento.',
    penaltyUse: 'Nao calcular valor. Usar apenas como referencia para demonstrar aderencia geral ao GRO e rastreabilidade.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-02',
    title: 'Inspecao Previa',
    status: 'revogada',
    category: 'revogada',
    package: 'Base SST',
    relatedContexts: ['base_sst'],
    relatedCriticalActivities: [],
    operationalUse: 'Nao usar como motor. Manter apenas historico de referencia.',
    penaltyUse: 'Sem uso operacional atual.',
    note: 'Revogada na lista oficial do MTE.',
    active: false,
  },
  {
    id: 'NR-03',
    title: 'Embargo e Interdicao',
    status: 'vigente',
    category: 'especial',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'construcao', 'industria', 'porto', 'rural'],
    relatedCriticalActivities: ['altura', 'eletricidade', 'maquinas', 'espaco_confinado', 'incendio', 'movimentacao_cargas', 'produtos_quimicos'],
    operationalUse: 'Referencia para sinalizar bloqueio e gravidade operacional extrema.',
    penaltyUse: 'Referencia de escalacao de risco grave e iminente; nao calcular sancao.',
    note: 'Usar como contexto de bloqueio, nao como workflow juridico.',
    active: true,
  },
  {
    id: 'NR-04',
    title: 'Servicos Especializados em Seguranca e em Medicina do Trabalho',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst'],
    relatedCriticalActivities: [],
    operationalUse: 'Referencia para papeis tecnicos, ownership e suporte especializado.',
    penaltyUse: 'Referencia futura de auditoria documental.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-05',
    title: 'Comissao Interna de Prevencao de Acidentes',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst'],
    relatedCriticalActivities: [],
    operationalUse: 'Contexto para participacao, observacoes recorrentes e melhoria continua.',
    penaltyUse: 'Referencia futura de fiscalizacao documental.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-06',
    title: 'Equipamento de Protecao Individual - EPI',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'industria', 'construcao', 'logistica', 'facilities', 'porto', 'saude', 'rural', 'manutencao'],
    relatedCriticalActivities: ['altura', 'eletricidade', 'maquinas', 'espaco_confinado', 'incendio', 'movimentacao_cargas', 'produtos_quimicos'],
    operationalUse: 'Acionar triagem e exigencia de evidencia quando houver ausencia ou inadequacao de EPI.',
    penaltyUse: 'Somente referencia futura de fiscalizacao; sem valor definitivo.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-07',
    title: 'Programa de Controle Medico de Saude Ocupacional',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'saude', 'industria', 'rural'],
    relatedCriticalActivities: ['produtos_quimicos', 'ergonomia'],
    operationalUse: 'Contexto para encaminhamento de rastreabilidade medica e monitoramento de exposicao.',
    penaltyUse: 'Referencia futura para auditoria documental, nao para calculo.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-08',
    title: 'Edificacoes',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['facilities', 'industria', 'construcao', 'saude'],
    relatedCriticalActivities: ['incendio', 'ergonomia'],
    operationalUse: 'Contexto para condicoes fisicas de predio, acessos e conservacao.',
    penaltyUse: 'Referencia futura de nao conformidade estrutural.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-09',
    title: 'Avaliacao e Controle das Exposicoes Ocupacionais a Agentes Fisicos, Quimicos e Biologicos',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['industria', 'saude', 'rural', 'facilities', 'manutencao'],
    relatedCriticalActivities: ['produtos_quimicos', 'ergonomia'],
    operationalUse: 'Contexto para exposicao ocupacional, triagem de controles e rastreabilidade ambiental.',
    penaltyUse: 'Referencia futura para auditoria de exposicao, sem calculo final.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-10',
    title: 'Seguranca em Instalacoes e Servicos em Eletricidade',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['manutencao', 'industria', 'facilities', 'construcao', 'porto'],
    relatedCriticalActivities: ['eletricidade'],
    operationalUse: 'Base para prioridade critica, evidencia obrigatoria e bloqueio por energia perigosa.',
    penaltyUse: 'Referencia futura de fiscalizacao em eletricidade, sem valor juridico definitivo.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-11',
    title: 'Transporte, Movimentacao, Armazenagem e Manuseio de Materiais',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['logistica', 'industria', 'porto', 'rural'],
    relatedCriticalActivities: ['movimentacao_cargas'],
    operationalUse: 'Contexto para fluxo, carga, descarga, armazenagem e segregacao.',
    penaltyUse: 'Referencia futura de fiscalizacao operacional.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-12',
    title: 'Seguranca no Trabalho em Maquinas e Equipamentos',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'manutencao', 'construcao', 'rural'],
    relatedCriticalActivities: ['maquinas'],
    operationalUse: 'Base para bloqueio, triagem e rastreabilidade em maquinas e manutencao.',
    penaltyUse: 'Referencia futura de fiscalizacao tecnica.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-13',
    title: 'Caldeiras, Vasos de Pressao, Tubulacoes e Tanques Metalicos de Armazenamento',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'manutencao'],
    relatedCriticalActivities: ['produtos_quimicos'],
    operationalUse: 'Contexto para integridade mecanica, inspeções e liberacoes especiais.',
    penaltyUse: 'Referencia futura de fiscalizacao tecnica.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-14',
    title: 'Fornos',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria'],
    relatedCriticalActivities: ['incendio', 'produtos_quimicos'],
    operationalUse: 'Contexto para calor, processo termico e controles especiais.',
    penaltyUse: 'Referencia futura de fiscalizacao setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-15',
    title: 'Atividades e Operacoes Insalubres',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'saude', 'rural', 'facilities'],
    relatedCriticalActivities: ['produtos_quimicos', 'ergonomia'],
    operationalUse: 'Contexto para exposicoes relevantes e priorizacao de controle ocupacional.',
    penaltyUse: 'Referencia futura de auditoria ocupacional; nao calcular adicional.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-16',
    title: 'Atividades e Operacoes Perigosas',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'porto', 'manutencao', 'rural'],
    relatedCriticalActivities: ['eletricidade', 'incendio', 'produtos_quimicos'],
    operationalUse: 'Contexto para priorizar desvio com potencial severo e bloqueio.',
    penaltyUse: 'Referencia futura de fiscalizacao; nao calcular adicional legal.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-17',
    title: 'Ergonomia',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'industria', 'logistica', 'facilities', 'saude'],
    relatedCriticalActivities: ['ergonomia'],
    operationalUse: 'Base para triagem de posto inadequado, repetitividade e fadiga operacional.',
    penaltyUse: 'Referencia futura de auditoria ergonomica.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-18',
    title: 'Seguranca e Saude no Trabalho na Industria da Construcao',
    status: 'vigente',
    category: 'setorial',
    package: 'Construcao Civil',
    relatedContexts: ['construcao', 'facilities', 'manutencao'],
    relatedCriticalActivities: ['altura', 'incendio', 'movimentacao_cargas', 'produtos_quimicos'],
    operationalUse: 'Base operacional de obra para isolamento, acesso, andaime e escavacao.',
    penaltyUse: 'Referencia futura de fiscalizacao em obra.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-19',
    title: 'Explosivos',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'porto', 'rural'],
    relatedCriticalActivities: ['incendio', 'produtos_quimicos'],
    operationalUse: 'Contexto de alto potencial para triagem e bloqueio de processo.',
    penaltyUse: 'Referencia futura de fiscalizacao especializada.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-20',
    title: 'Seguranca e Saude no Trabalho com Inflamaveis e Combustiveis',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'porto', 'facilities', 'manutencao'],
    relatedCriticalActivities: ['incendio', 'produtos_quimicos'],
    operationalUse: 'Contexto para inflamaveis, segregacao, permissao e emergencia.',
    penaltyUse: 'Referencia futura de fiscalizacao de seguranca de processo.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-21',
    title: 'Trabalhos a Ceu Aberto',
    status: 'vigente',
    category: 'especial',
    package: 'Base SST',
    relatedContexts: ['rural', 'construcao', 'porto', 'facilities'],
    relatedCriticalActivities: ['ergonomia'],
    operationalUse: 'Contexto para exposicao climatica, abrigo e condicoes de apoio.',
    penaltyUse: 'Referencia futura de fiscalizacao contextual.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-22',
    title: 'Seguranca e Saude Ocupacional na Mineracao',
    status: 'vigente',
    category: 'setorial',
    package: 'Industria',
    relatedContexts: ['industria', 'rural'],
    relatedCriticalActivities: ['movimentacao_cargas', 'produtos_quimicos', 'incendio'],
    operationalUse: 'Contexto setorial para operacoes de mineracao e frentes de extração.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-23',
    title: 'Protecao Contra Incendios',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'industria', 'construcao', 'logistica', 'facilities', 'porto', 'saude', 'rural', 'manutencao'],
    relatedCriticalActivities: ['incendio'],
    operationalUse: 'Base para acessibilidade de combate, rotas de fuga e prontidao.',
    penaltyUse: 'Referencia futura de fiscalizacao de emergencia.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-24',
    title: 'Condicoes Sanitarias e de Conforto nos Locais de Trabalho',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'facilities', 'saude', 'rural', 'construcao'],
    relatedCriticalActivities: ['ergonomia'],
    operationalUse: 'Contexto para apoio, conforto e condicoes sanitarias minimas.',
    penaltyUse: 'Referencia futura documental e de campo.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-25',
    title: 'Residuos Industriais',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'logistica', 'facilities', 'saude'],
    relatedCriticalActivities: ['produtos_quimicos'],
    operationalUse: 'Contexto para segregacao, descarte, armazenamento e rastreabilidade de residuos.',
    penaltyUse: 'Referencia futura de fiscalizacao ambiental ocupacional.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-26',
    title: 'Sinalizacao de Seguranca',
    status: 'vigente',
    category: 'geral',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'industria', 'construcao', 'logistica', 'facilities', 'porto', 'saude', 'rural', 'manutencao'],
    relatedCriticalActivities: ['incendio', 'movimentacao_cargas', 'produtos_quimicos'],
    operationalUse: 'Contexto para sinalizacao, identificacao e orientacao visivel no campo.',
    penaltyUse: 'Referencia futura de fiscalizacao visual e documental.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-27',
    title: 'Registro Profissional do Tecnico de Seguranca do Trabalho',
    status: 'revogada',
    category: 'revogada',
    package: 'Base SST',
    relatedContexts: ['base_sst'],
    relatedCriticalActivities: [],
    operationalUse: 'Nao usar como motor. Manter apenas referencia historica.',
    penaltyUse: 'Sem uso operacional atual.',
    note: 'Revogada na lista oficial do MTE.',
    active: false,
  },
  {
    id: 'NR-28',
    title: 'Fiscalizacao e Penalidades',
    status: 'vigente',
    category: 'penalidade',
    package: 'Base SST',
    relatedContexts: ['base_sst', 'industria', 'construcao', 'logistica', 'facilities', 'porto', 'saude', 'rural', 'manutencao'],
    relatedCriticalActivities: ['altura', 'eletricidade', 'maquinas', 'espaco_confinado', 'incendio', 'ergonomia', 'movimentacao_cargas', 'produtos_quimicos'],
    operationalUse: 'Usar apenas como referencia futura de fiscalizacao e priorizacao documental; nao e motor principal.',
    penaltyUse: 'Nao calcular multa final. Usar apenas para sinalizar possibilidade futura de penalidade/fiscalizacao.',
    note: 'Tratada como referencia futura, conforme diretriz do produto.',
    active: true,
  },
  {
    id: 'NR-29',
    title: 'Norma Regulamentadora de Seguranca e Saude no Trabalho Portuario',
    status: 'vigente',
    category: 'setorial',
    package: 'Portuario',
    relatedContexts: ['porto', 'logistica'],
    relatedCriticalActivities: ['movimentacao_cargas', 'incendio', 'produtos_quimicos'],
    operationalUse: 'Contexto setorial de operacao portuaria e frentes de carga.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-30',
    title: 'Seguranca e Saude no Trabalho Aquaviario',
    status: 'vigente',
    category: 'setorial',
    package: 'Portuario',
    relatedContexts: ['porto'],
    relatedCriticalActivities: ['movimentacao_cargas', 'incendio', 'produtos_quimicos'],
    operationalUse: 'Contexto para operacao embarcada e apoio aquaviario.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-31',
    title: 'Seguranca e Saude no Trabalho na Agricultura, Pecuaria Silvicultura, Exploracao Florestal e Aquicultura',
    status: 'vigente',
    category: 'setorial',
    package: 'Rural',
    relatedContexts: ['rural'],
    relatedCriticalActivities: ['movimentacao_cargas', 'produtos_quimicos', 'ergonomia'],
    operationalUse: 'Contexto setorial rural para triagem de campo e organizacao operacional.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-32',
    title: 'Seguranca e Saude no Trabalho em Servicos de Saude',
    status: 'vigente',
    category: 'setorial',
    package: 'Saude/Hospitalar',
    relatedContexts: ['saude'],
    relatedCriticalActivities: ['produtos_quimicos', 'ergonomia', 'incendio'],
    operationalUse: 'Contexto setorial para servicos de saude, exposicao e rastreabilidade operacional.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-33',
    title: 'Seguranca e Saude nos Trabalhos em Espacos Confinados',
    status: 'vigente',
    category: 'especial',
    package: 'Industria',
    relatedContexts: ['industria', 'manutencao', 'construcao', 'facilities'],
    relatedCriticalActivities: ['espaco_confinado'],
    operationalUse: 'Base para bloqueio imediato, evidencia, permissao e resgate em espaco confinado.',
    penaltyUse: 'Referencia futura de fiscalizacao especializada.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-34',
    title: 'Condicoes e Meio Ambiente de Trabalho na Industria da Construcao, Reparacao e Desmonte Naval',
    status: 'vigente',
    category: 'setorial',
    package: 'Portuario',
    relatedContexts: ['porto', 'manutencao', 'industria'],
    relatedCriticalActivities: ['incendio', 'altura', 'produtos_quimicos'],
    operationalUse: 'Contexto setorial para construcao e reparacao naval.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-35',
    title: 'Trabalho em Altura',
    status: 'vigente',
    category: 'especial',
    package: 'Construcao Civil',
    relatedContexts: ['construcao', 'facilities', 'manutencao', 'industria', 'porto'],
    relatedCriticalActivities: ['altura'],
    operationalUse: 'Base para triagem critica, bloqueio e exigencia de evidencia em altura.',
    penaltyUse: 'Referencia futura de fiscalizacao especializada.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-36',
    title: 'Seguranca e Saude no Trabalho em Empresas de Abate e Processamento de Carnes e Derivados',
    status: 'vigente',
    category: 'setorial',
    package: 'Industria',
    relatedContexts: ['industria'],
    relatedCriticalActivities: ['ergonomia', 'maquinas', 'produtos_quimicos'],
    operationalUse: 'Contexto setorial para linha frigorifica e processamento de carnes.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-37',
    title: 'Seguranca e Saude em Plataformas de Petroleo',
    status: 'vigente',
    category: 'setorial',
    package: 'Industria',
    relatedContexts: ['porto', 'industria'],
    relatedCriticalActivities: ['incendio', 'produtos_quimicos', 'movimentacao_cargas', 'altura'],
    operationalUse: 'Contexto setorial offshore para risco maior e disciplina operacional.',
    penaltyUse: 'Referencia futura setorial.',
    note: NR_SOURCE_NOTE,
    active: true,
  },
  {
    id: 'NR-38',
    title: 'Seguranca e Saude no Trabalho nas Atividades de Limpeza Urbana e Manejo de Residuos Solidos',
    status: 'vigente',
    category: 'setorial',
    package: 'Base SST',
    relatedContexts: ['facilities', 'saude', 'logistica'],
    relatedCriticalActivities: ['movimentacao_cargas', 'produtos_quimicos', 'incendio', 'ergonomia'],
    operationalUse: 'Contexto setorial para limpeza urbana, manejo de residuos e apoio operacional correlato.',
    penaltyUse: 'Referencia futura de fiscalizacao; nao calcular sancao nem valor.',
    note: 'Texto vigente do MTE atualizado em 27/05/2025 no portal oficial.',
    active: true,
  },
];

export const NR_CATALOG_COUNT = NR_CATALOG.length;

export function getNrCatalogEntry(nrId: string): NRCatalogEntry | undefined {
  return NR_CATALOG.find((entry) => entry.id === nrId);
}
