import type { OperationalContext } from '@/src/types/operationalContext';

export const OPERATIONAL_CONTEXTS: OperationalContext[] = [
  {
    id: 'linha-producao',
    name: 'Linha de producao',
    kind: 'fabrica',
    keywords: ['linha', 'producao', 'esteira', 'posto', 'celula'],
    hazardClasses: ['aprisionamento', 'ruido', 'movimento'],
    applicableNrs: ['NR-01', 'NR-12', 'NR-17'],
    requiredDocuments: ['APR', 'procedimento operacional'],
    active: true,
  },
  {
    id: 'oficina-manutencao',
    name: 'Oficina de manutencao',
    kind: 'oficina',
    keywords: ['oficina', 'manutencao', 'bancada', 'ferramenta', 'torno'],
    hazardClasses: ['mecanico', 'eletrico', 'energia residual'],
    applicableNrs: ['NR-01', 'NR-10', 'NR-12'],
    requiredDocuments: ['APR', 'LOTO', 'procedimento'],
    active: true,
  },
  {
    id: 'almoxarifado-logistico',
    name: 'Almoxarifado logistico',
    kind: 'almoxarifado',
    keywords: ['almoxarifado', 'estoque', 'prateleira', 'picking'],
    hazardClasses: ['movimentacao de carga', 'queda de material'],
    applicableNrs: ['NR-01', 'NR-11', 'NR-17'],
    requiredDocuments: ['inventario de armazenagem'],
    active: true,
  },
  {
    id: 'patio-carga',
    name: 'Patio de carga',
    kind: 'patio',
    keywords: ['patio', 'carga', 'descarga', 'caminhao', 'empilhadeira'],
    hazardClasses: ['atropelamento', 'movimentacao de carga'],
    applicableNrs: ['NR-01', 'NR-11'],
    requiredDocuments: ['plano de trafego'],
    active: true,
  },
  {
    id: 'subestacao-eletrica',
    name: 'Subestacao eletrica',
    kind: 'subestacao',
    keywords: ['subestacao', 'painel', 'cabine eletrica', 'energizado'],
    hazardClasses: ['choque eletrico', 'arco eletrico'],
    applicableNrs: ['NR-01', 'NR-10'],
    requiredDocuments: ['prontuario eletrico', 'APR', 'PT'],
    active: true,
  },
  {
    id: 'trabalho-altura',
    name: 'Frente de trabalho em altura',
    kind: 'altura',
    keywords: ['altura', 'telhado', 'andaime', 'escada', 'fachada'],
    hazardClasses: ['queda de altura', 'queda de materiais'],
    applicableNrs: ['NR-01', 'NR-35'],
    requiredDocuments: ['APR', 'PT', 'plano de resgate'],
    active: true,
  },
  {
    id: 'espaco-confinado',
    name: 'Espaco confinado',
    kind: 'espaco confinado',
    keywords: ['espaco confinado', 'tanque', 'silo', 'galeria', 'poço', 'poco'],
    hazardClasses: ['asfixia', 'atmosfera perigosa', 'resgate'],
    applicableNrs: ['NR-01', 'NR-33'],
    requiredDocuments: ['PET', 'APR', 'plano de resgate'],
    active: true,
  },
  {
    id: 'cabine-pintura',
    name: 'Cabine de pintura',
    kind: 'cabine',
    keywords: ['cabine', 'pintura', 'solvente', 'tinta'],
    hazardClasses: ['inalacao', 'inflamavel'],
    applicableNrs: ['NR-01', 'NR-15', 'NR-20'],
    requiredDocuments: ['FISPQ', 'APR'],
    active: true,
  },
  {
    id: 'escritorio-operacional',
    name: 'Escritorio operacional',
    kind: 'escritorio',
    keywords: ['escritorio', 'administrativo', 'mesa', 'monitor'],
    hazardClasses: ['ergonomia'],
    applicableNrs: ['NR-01', 'NR-17'],
    requiredDocuments: ['AET'],
    active: true,
  },
];

export function getOperationalContextById(contextId: string): OperationalContext | undefined {
  return OPERATIONAL_CONTEXTS.find((context) => context.id === contextId);
}
