// Auto-generated normative checklists
import { ChecklistTemplate } from './store';

export const fixedNrChecklists: any[] = [
  {
    id: 'fixo-nr-01',
    name: 'Checklist Geral de Gerenciamento de Riscos — NR-01',
    category: 'Gerenciamento de Riscos',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-01',
        title: 'Verificação NR-01',
        questions: [
          {
            id: 'nr-01-01',
            text: 'O perigo da atividade foi identificado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-01',
            regraId: 'nr-01-01',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-01-02',
            text: 'O risco foi avaliado e classificado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-01',
            regraId: 'nr-01-02',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-01-03',
            text: 'Existe medida de controle definida?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-01',
            regraId: 'nr-01-05',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-01-04',
            text: 'Existe responsável pelo tratamento?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-01',
            regraId: 'nr-01-04',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-01-05',
            text: 'Existe plano de ação vinculado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-01',
            regraId: 'nr-01-03',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-06',
    name: 'Checklist de EPI — NR-06',
    category: 'EPI',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-06',
        title: 'Verificação NR-06',
        questions: [
          {
            id: 'nr-06-01',
            text: 'O trabalhador está utilizando o EPI obrigatório?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-06',
            regraId: 'nr-06-06',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-06-02',
            text: 'O EPI está adequado ao risco?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-06',
            regraId: 'nr-06-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-06-03',
            text: 'O EPI está em bom estado de conservação?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-06',
            regraId: 'nr-06-03',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-06-04',
            text: 'Existe registro de entrega do EPI?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-06',
            regraId: 'nr-06-04',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-06-05',
            text: 'O trabalhador recebeu orientação de uso?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-06',
            regraId: 'nr-06-05',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-07',
    name: 'Checklist de Saúde Ocupacional / ASO — NR-07',
    category: 'Saúde Ocupacional',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-07',
        title: 'Verificação NR-07',
        questions: [
          {
            id: 'nr-07-01',
            text: 'O trabalhador possui ASO válido?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-07',
            regraId: 'nr-07-01',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-07-02',
            text: 'O exame ocupacional está compatível com o risco?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-07',
            regraId: 'nr-07-05',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-07-03',
            text: 'Há controle médico para exposição identificada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-07',
            regraId: 'nr-07-04',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-07-04',
            text: 'Existe pendência de exame ocupacional?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-07',
            regraId: 'nr-07-03',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-07-05',
            text: 'O trabalhador está apto para a atividade?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-07',
            regraId: 'nr-07-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-10',
    name: 'Checklist de Serviços Elétricos — NR-10',
    category: 'Elétrica',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-10',
        title: 'Verificação NR-10',
        questions: [
          {
            id: 'nr-10-01',
            text: 'O serviço elétrico possui procedimento definido?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-10',
            regraId: 'nr-10-03',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-10-02',
            text: 'A fonte de energia foi bloqueada/desenergizada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-10',
            regraId: 'nr-10-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-10-03',
            text: 'Existe sinalização de área energizada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-10',
            regraId: 'nr-10-05',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-10-04',
            text: 'O trabalhador possui qualificação/capacitação aplicável?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-10',
            regraId: 'nr-10-04',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-10-05',
            text: 'Há risco de choque elétrico ou arco elétrico sem controle?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-10',
            regraId: 'nr-10-06',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-11',
    name: 'Checklist de Movimentação de Materiais — NR-11',
    category: 'Movimentação e Cargas',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-11',
        title: 'Verificação NR-11',
        questions: [
          {
            id: 'nr-11-01',
            text: 'A movimentação de carga possui procedimento?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-11',
            regraId: 'nr-11-01',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-11-02',
            text: 'O operador está autorizado/capacitado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-11',
            regraId: 'nr-11-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-11-03',
            text: 'O equipamento de movimentação está em condição segura?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-11',
            regraId: 'nr-11-02',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-11-04',
            text: 'A carga está armazenada de forma segura?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-11',
            regraId: 'nr-11-04',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-11-05',
            text: 'Existe risco de queda, esmagamento ou atropelamento?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-11',
            regraId: 'nr-11-05',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-12',
    name: 'Checklist de Máquinas e Equipamentos — NR-12',
    category: 'Máquinas e Equipamentos',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-12',
        title: 'Verificação NR-12',
        questions: [
          {
            id: 'nr-12-01',
            text: 'A máquina possui proteção física adequada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-12',
            regraId: 'nr-12-01',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-12-02',
            text: 'A zona de risco está inacessível durante a operação?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-12',
            regraId: 'nr-12-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-12-03',
            text: 'Existe dispositivo de parada/emergência funcional?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-12',
            regraId: 'nr-12-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-12-04',
            text: 'A manutenção possui bloqueio/controle de energia?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-12',
            regraId: 'nr-12-04',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-12-05',
            text: 'Há risco de corte, esmagamento, aprisionamento ou projeção?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-12',
            regraId: 'nr-12-06',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-17',
    name: 'Checklist de Ergonomia — NR-17',
    category: 'Ergonomia',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-17',
        title: 'Verificação NR-17',
        questions: [
          {
            id: 'nr-17-01',
            text: 'A postura de trabalho é adequada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-17',
            regraId: 'nr-17-01',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-17-02',
            text: 'Há repetitividade ou esforço excessivo?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-17',
            regraId: 'nr-17-02',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-17-03',
            text: 'O mobiliário/posto está ajustado à atividade?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-17',
            regraId: 'nr-17-03',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-17-04',
            text: 'Há levantamento manual de carga sem controle?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-17',
            regraId: 'nr-17-04',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-17-05',
            text: 'O ritmo de trabalho gera sobrecarga?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-17',
            regraId: 'nr-17-05',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-18',
    name: 'Checklist de Construção / Canteiro — NR-18',
    category: 'Construção Civil',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-18',
        title: 'Verificação NR-18',
        questions: [
          {
            id: 'nr-18-01',
            text: 'Existem proteções coletivas instaladas?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-18',
            regraId: 'nr-18-01',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-18-02',
            text: 'A área está isolada e sinalizada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-18',
            regraId: 'nr-18-02',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-18-03',
            text: 'Andaimes/plataformas estão em condição segura?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-18',
            regraId: 'nr-18-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-18-04',
            text: 'Há controle contra queda de materiais?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-18',
            regraId: 'nr-18-05',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-18-05',
            text: 'O canteiro está organizado e com acesso seguro?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-18',
            regraId: 'nr-18-07',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-20',
    name: 'Checklist de Inflamáveis e Combustíveis — NR-20',
    category: 'Inflamáveis',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-20',
        title: 'Verificação NR-20',
        questions: [
          {
            id: 'nr-20-01',
            text: 'O armazenamento de inflamáveis está adequado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-20',
            regraId: 'nr-20-01',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-20-02',
            text: 'Fontes de ignição estão controladas?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-20',
            regraId: 'nr-20-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-20-03',
            text: 'Existe sinalização de risco de incêndio/explosão?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-20',
            regraId: 'nr-20-03',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-20-04',
            text: 'Existe procedimento para manuseio?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-20',
            regraId: 'nr-20-07',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-20-05',
            text: 'Existe plano de emergência aplicável?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-20',
            regraId: 'nr-20-04',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-23',
    name: 'Checklist de Incêndio e Emergência — NR-23',
    category: 'Emergência',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-23',
        title: 'Verificação NR-23',
        questions: [
          {
            id: 'nr-23-01',
            text: 'Os extintores estão disponíveis e válidos?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-23',
            regraId: 'nr-23-01',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-23-02',
            text: 'Rotas de fuga estão livres e sinalizadas?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-23',
            regraId: 'nr-23-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-23-03',
            text: 'Saídas de emergência estão desobstruídas?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-23',
            regraId: 'nr-23-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-23-04',
            text: 'Há treinamento/orientação para emergência?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-23',
            regraId: 'nr-23-05',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-23-05',
            text: 'Alarmes/equipamentos de emergência estão disponíveis?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-23',
            regraId: 'nr-23-06',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-26',
    name: 'Checklist de Produtos Químicos e Sinalização — NR-26',
    category: 'Produtos Químicos',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-26',
        title: 'Verificação NR-26',
        questions: [
          {
            id: 'nr-26-01',
            text: 'Produtos químicos estão identificados/rotulados?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-26',
            regraId: 'nr-26-01',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-26-02',
            text: 'Existe FISPQ/FDS disponível?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Média',
            nrRelacionada: 'NR-26',
            regraId: 'nr-26-03',
            criticidade: 'Média',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-26-03',
            text: 'A sinalização de risco está adequada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-26',
            regraId: 'nr-26-04',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-26-04',
            text: 'O armazenamento químico está segregado e seguro?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-26',
            regraId: 'nr-26-05',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-26-05',
            text: 'Há risco de exposição química sem controle?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-26',
            regraId: 'nr-26-06',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-33',
    name: 'Checklist de Espaço Confinado — NR-33',
    category: 'Espaço Confinado',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-33',
        title: 'Verificação NR-33',
        questions: [
          {
            id: 'nr-33-01',
            text: 'Existe permissão de entrada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-33',
            regraId: 'nr-33-01',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-33-02',
            text: 'Há vigia designado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-33',
            regraId: 'nr-33-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-33-03',
            text: 'A atmosfera foi avaliada/monitorada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-33',
            regraId: 'nr-33-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-33-04',
            text: 'Existe plano de resgate?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-33',
            regraId: 'nr-33-04',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-33-05',
            text: 'Os trabalhadores possuem capacitação?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-33',
            regraId: 'nr-33-05',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-33-06',
            text: 'A ventilação é adequada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-33',
            regraId: 'nr-33-06',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  },
  {
    id: 'fixo-nr-35',
    name: 'Checklist de Trabalho em Altura — NR-35',
    category: 'Segurança',
    status: 'Ativo',
    regraFixa: true,
    editavel: false,
    removivel: false,
    sections: [
      {
        id: 'sec-nr-35',
        title: 'Verificação NR-35',
        questions: [
          {
            id: 'nr-35-01',
            text: 'Existe permissão/procedimento para a atividade?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-35',
            regraId: 'nr-35-06',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-35-02',
            text: 'O trabalhador possui capacitação aplicável?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-35',
            regraId: 'nr-35-05',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-35-03',
            text: 'Há linha de vida instalada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-35',
            regraId: 'nr-35-01',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-35-04',
            text: 'Há ponto de ancoragem adequado?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-35',
            regraId: 'nr-35-02',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-35-05',
            text: 'O trabalhador usa cinto/trava-quedas?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Crítica',
            nrRelacionada: 'NR-35',
            regraId: 'nr-35-03',
            criticidade: 'Crítica',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: true,
            regraFixa: true,
            editavel: false,
            removivel: false
          },
          {
            id: 'nr-35-06',
            text: 'A área inferior está isolada e sinalizada?',
            type: 'Sim / Não / Parcialmente',
            riskMap: 'Alta',
            nrRelacionada: 'NR-35',
            regraId: 'nr-35-04',
            criticidade: 'Alta',
            tipoRisco: 'Segurança Ocupacional',
            geraRisco: true,
            geraAcao: true,
            impactaScore: true,
            bloqueante: false,
            regraFixa: true,
            editavel: false,
            removivel: false
          }
        ]
      }
    ]
  }
];

export function getTodosChecklistsAtivos(customChecklists: any[]) {
  const customIds = new Set(fixedNrChecklists.map(c => c.id));
  const filteredCustom = (customChecklists || []).filter(c => !customIds.has(c.id));
  return [...filteredCustom, ...fixedNrChecklists];
}
