export const fixedNrRules = [
  {
    "id": "nr-01-01",
    "nr": "NR-01",
    "titulo": "Perigo não identificado",
    "descricao": "O perigo no ambiente de trabalho não foi identificado ou relatado no PGR.",
    "atividadeRelacionada": "Atividades mapeadas na NR-01",
    "perigo": "Perigo não identificado",
    "tipoRisco": "Administrativo",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Perigo não identificado?"
    ],
    "condicaoDeNaoConformidade": "Perigo não identificado",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 15,
    "multaBaseEstimativa": 10000,
    "chanceIncidenteBase": 65,
    "acaoRecomendada": "Este risco foi gerado com base na NR-01 porque foi identificado: Perigo não identificado.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-01-02",
    "nr": "NR-01",
    "titulo": "Risco sem avaliação",
    "descricao": "Os riscos identificados não passaram por processo de avaliação ou gradação.",
    "atividadeRelacionada": "Atividades mapeadas na NR-01",
    "perigo": "Risco sem avaliação",
    "tipoRisco": "Administrativo",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco sem avaliação?"
    ],
    "condicaoDeNaoConformidade": "Risco sem avaliação",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 15,
    "multaBaseEstimativa": 10000,
    "chanceIncidenteBase": 65,
    "acaoRecomendada": "Este risco foi gerado com base na NR-01 porque foi identificado: Risco sem avaliação.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-01-03",
    "nr": "NR-01",
    "titulo": "Ausência de plano de ação",
    "descricao": "Não há plano de ação definido para mitigar ou eliminar os riscos identificados.",
    "atividadeRelacionada": "Atividades mapeadas na NR-01",
    "perigo": "Ausência de plano de ação",
    "tipoRisco": "Administrativo",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de plano de ação?"
    ],
    "condicaoDeNaoConformidade": "Ausência de plano de ação",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 15,
    "multaBaseEstimativa": 10000,
    "chanceIncidenteBase": 65,
    "acaoRecomendada": "Este risco foi gerado com base na NR-01 porque foi identificado: Ausência de plano de ação.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-01-04",
    "nr": "NR-01",
    "titulo": "Risco sem responsável",
    "descricao": "As medidas de controle do risco não possuem um responsável designado.",
    "atividadeRelacionada": "Atividades mapeadas na NR-01",
    "perigo": "Risco sem responsável",
    "tipoRisco": "Administrativo",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco sem responsável?"
    ],
    "condicaoDeNaoConformidade": "Risco sem responsável",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 15,
    "multaBaseEstimativa": 10000,
    "chanceIncidenteBase": 65,
    "acaoRecomendada": "Este risco foi gerado com base na NR-01 porque foi identificado: Risco sem responsável.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-01-05",
    "nr": "NR-01",
    "titulo": "Risco sem medida de controle",
    "descricao": "Não existem medidas de controle estabelecidas para mitigar o risco ocupacional.",
    "atividadeRelacionada": "Atividades mapeadas na NR-01",
    "perigo": "Risco sem controle",
    "tipoRisco": "Administrativo",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco sem medida de controle?"
    ],
    "condicaoDeNaoConformidade": "Risco sem controle",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 15,
    "multaBaseEstimativa": 10000,
    "chanceIncidenteBase": 65,
    "acaoRecomendada": "Este risco foi gerado com base na NR-01 porque foi identificado: Risco sem medida de controle.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-01-06",
    "nr": "NR-01",
    "titulo": "Ausência de acompanhamento de risco",
    "descricao": "Falta monitoramento e revisão contínua das medidas de controle adotadas.",
    "atividadeRelacionada": "Atividades mapeadas na NR-01",
    "perigo": "Falta acompanhamento",
    "tipoRisco": "Administrativo",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de acompanhamento de risco?"
    ],
    "condicaoDeNaoConformidade": "Falta acompanhamento",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 15,
    "multaBaseEstimativa": 10000,
    "chanceIncidenteBase": 65,
    "acaoRecomendada": "Este risco foi gerado com base na NR-01 porque foi identificado: Ausência de acompanhamento de risco.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-06-01",
    "nr": "NR-06",
    "titulo": "EPI ausente",
    "descricao": "Ausência de fornecimento de EPI necessário para a atividade.",
    "atividadeRelacionada": "Atividades mapeadas na NR-06",
    "perigo": "EPI não fornecido",
    "tipoRisco": "Físico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: EPI ausente?"
    ],
    "condicaoDeNaoConformidade": "EPI não fornecido",
    "severidadeBase": "Alta",
    "prioridadeBase": "Urgente",
    "prazoBase": 2,
    "multaBaseEstimativa": 8000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-06 porque foi identificado: EPI ausente.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-06-02",
    "nr": "NR-06",
    "titulo": "EPI inadequado",
    "descricao": "O EPI fornecido não é adequado ao risco da atividade.",
    "atividadeRelacionada": "Atividades mapeadas na NR-06",
    "perigo": "EPI incompatível",
    "tipoRisco": "Físico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: EPI inadequado?"
    ],
    "condicaoDeNaoConformidade": "EPI incompatível",
    "severidadeBase": "Alta",
    "prioridadeBase": "Urgente",
    "prazoBase": 2,
    "multaBaseEstimativa": 8000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-06 porque foi identificado: EPI inadequado.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-06-03",
    "nr": "NR-06",
    "titulo": "EPI vencido",
    "descricao": "O certificado de aprovação (CA) ou a validade do equipamento está expirada.",
    "atividadeRelacionada": "Atividades mapeadas na NR-06",
    "perigo": "EPI vencido",
    "tipoRisco": "Físico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: EPI vencido?"
    ],
    "condicaoDeNaoConformidade": "EPI vencido",
    "severidadeBase": "Alta",
    "prioridadeBase": "Urgente",
    "prazoBase": 2,
    "multaBaseEstimativa": 8000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-06 porque foi identificado: EPI vencido.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-06-04",
    "nr": "NR-06",
    "titulo": "EPI sem registro de entrega",
    "descricao": "Falta registro e controle rigoroso do fornecimento de EPI aos colaboradores.",
    "atividadeRelacionada": "Atividades mapeadas na NR-06",
    "perigo": "Ficha de EPI desatualizada",
    "tipoRisco": "Físico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: EPI sem registro de entrega?"
    ],
    "condicaoDeNaoConformidade": "Ficha de EPI desatualizada",
    "severidadeBase": "Alta",
    "prioridadeBase": "Urgente",
    "prazoBase": 2,
    "multaBaseEstimativa": 8000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-06 porque foi identificado: EPI sem registro de entrega.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-06-05",
    "nr": "NR-06",
    "titulo": "EPI sem orientação de uso",
    "descricao": "Ausência de treinamento sobre uso, guarda e conservação correta do EPI.",
    "atividadeRelacionada": "Atividades mapeadas na NR-06",
    "perigo": "Sem orientação EPI",
    "tipoRisco": "Físico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: EPI sem orientação de uso?"
    ],
    "condicaoDeNaoConformidade": "Sem orientação EPI",
    "severidadeBase": "Alta",
    "prioridadeBase": "Urgente",
    "prazoBase": 2,
    "multaBaseEstimativa": 8000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-06 porque foi identificado: EPI sem orientação de uso.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-06-06",
    "nr": "NR-06",
    "titulo": "Trabalhador não utilizando EPI obrigatório",
    "descricao": "O uso do EPI obrigatório não está sendo inspecionado e cobrado do trabalhador.",
    "atividadeRelacionada": "Atividades mapeadas na NR-06",
    "perigo": "EPI não utilizado",
    "tipoRisco": "Físico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Trabalhador não utilizando EPI obrigatório?"
    ],
    "condicaoDeNaoConformidade": "EPI não utilizado",
    "severidadeBase": "Alta",
    "prioridadeBase": "Urgente",
    "prazoBase": 2,
    "multaBaseEstimativa": 8000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-06 porque foi identificado: Trabalhador não utilizando EPI obrigatório.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-07-01",
    "nr": "NR-07",
    "titulo": "ASO ausente",
    "descricao": "Trabalhador operando sem a emissão do Atestado de Saúde Ocupacional (ASO).",
    "atividadeRelacionada": "Atividades mapeadas na NR-07",
    "perigo": "Falta ASO",
    "tipoRisco": "Saúde Ocupacional",
    "perguntasChecklist": [
      "Houve irregularidade referente a: ASO ausente?"
    ],
    "condicaoDeNaoConformidade": "Falta ASO",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 7,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 40,
    "acaoRecomendada": "Este risco foi gerado com base na NR-07 porque foi identificado: ASO ausente.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-07-02",
    "nr": "NR-07",
    "titulo": "ASO vencido",
    "descricao": "O ASO do trabalhador encontra-se com prazo de validade expirado.",
    "atividadeRelacionada": "Atividades mapeadas na NR-07",
    "perigo": "ASO vencido",
    "tipoRisco": "Saúde Ocupacional",
    "perguntasChecklist": [
      "Houve irregularidade referente a: ASO vencido?"
    ],
    "condicaoDeNaoConformidade": "ASO vencido",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 7,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 40,
    "acaoRecomendada": "Este risco foi gerado com base na NR-07 porque foi identificado: ASO vencido.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-07-03",
    "nr": "NR-07",
    "titulo": "Exame ocupacional pendente",
    "descricao": "Exames médicos ou complementares exigidos pelo PCMSO não foram realizados.",
    "atividadeRelacionada": "Atividades mapeadas na NR-07",
    "perigo": "Exames pendentes",
    "tipoRisco": "Saúde Ocupacional",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Exame ocupacional pendente?"
    ],
    "condicaoDeNaoConformidade": "Exames pendentes",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 7,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 40,
    "acaoRecomendada": "Este risco foi gerado com base na NR-07 porque foi identificado: Exame ocupacional pendente.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-07-04",
    "nr": "NR-07",
    "titulo": "Trabalhador exposto sem acompanhamento médico",
    "descricao": "Presença de trabalhador em área de risco específico sem acompanhamento.",
    "atividadeRelacionada": "Atividades mapeadas na NR-07",
    "perigo": "Falta monitoramento saúde",
    "tipoRisco": "Saúde Ocupacional",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Trabalhador exposto sem acompanhamento médico?"
    ],
    "condicaoDeNaoConformidade": "Falta monitoramento saúde",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 7,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 40,
    "acaoRecomendada": "Este risco foi gerado com base na NR-07 porque foi identificado: Trabalhador exposto sem acompanhamento médico.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-07-05",
    "nr": "NR-07",
    "titulo": "Ausência de vínculo entre risco ocupacional e controle médico",
    "descricao": "O PCMSO não mapeia os riscos apontados no PGR da respectiva área.",
    "atividadeRelacionada": "Atividades mapeadas na NR-07",
    "perigo": "PGR/PCMSO desvinculado",
    "tipoRisco": "Saúde Ocupacional",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de vínculo entre risco ocupacional e controle médico?"
    ],
    "condicaoDeNaoConformidade": "PGR/PCMSO desvinculado",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 7,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 40,
    "acaoRecomendada": "Este risco foi gerado com base na NR-07 porque foi identificado: Ausência de vínculo entre risco ocupacional e controle médico.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-01",
    "nr": "NR-10",
    "titulo": "Serviço elétrico sem bloqueio",
    "descricao": "Falta de adoção de bloqueio elétrico e desenergização prévia ao serviço.",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Sem LOTO",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Serviço elétrico sem bloqueio?"
    ],
    "condicaoDeNaoConformidade": "Sem LOTO",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Serviço elétrico sem bloqueio.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-02",
    "nr": "NR-10",
    "titulo": "Ausência de desenergização",
    "descricao": "Foi iniciada manutenção com o painel e os circuitos ainda energizados.",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Linha viva não autorizada",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de desenergização?"
    ],
    "condicaoDeNaoConformidade": "Linha viva não autorizada",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Ausência de desenergização.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-03",
    "nr": "NR-10",
    "titulo": "Ausência de procedimento",
    "descricao": "Não há procedimento claro de segurança (POP) para o serviço.",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Sem procedimento NR-10",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de procedimento?"
    ],
    "condicaoDeNaoConformidade": "Sem procedimento NR-10",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Ausência de procedimento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-04",
    "nr": "NR-10",
    "titulo": "Ausência de qualificação",
    "descricao": "Profissional realizando o serviço sem o devido treinamento de NR-10 ou habilitação.",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Sem qualificação NR-10",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de qualificação?"
    ],
    "condicaoDeNaoConformidade": "Sem qualificação NR-10",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Ausência de qualificação.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-05",
    "nr": "NR-10",
    "titulo": "Painel sem sinalização",
    "descricao": "Quadro de energia sem identificação e bloqueios de isolamento visual.",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Painel não sinalizado",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Painel sem sinalização?"
    ],
    "condicaoDeNaoConformidade": "Painel não sinalizado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Painel sem sinalização.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-06",
    "nr": "NR-10",
    "titulo": "Risco de choque elétrico",
    "descricao": "Exposição direta de colaborador a possíveis pontos elétricos energizados (choque elétrico).",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Risco iminente de choque",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de choque elétrico?"
    ],
    "condicaoDeNaoConformidade": "Risco iminente de choque",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Risco de choque elétrico.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-10-07",
    "nr": "NR-10",
    "titulo": "Risco de arco elétrico",
    "descricao": "Risco iminente devido ao uso de ferramentas ou EPIs em desacordo perto de alta tensão.",
    "atividadeRelacionada": "Atividades mapeadas na NR-10",
    "perigo": "Risco iminente de arco elétrico",
    "tipoRisco": "Elétrico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de arco elétrico?"
    ],
    "condicaoDeNaoConformidade": "Risco iminente de arco elétrico",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 25000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-10 porque foi identificado: Risco de arco elétrico.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-01",
    "nr": "NR-11",
    "titulo": "Movimentação de carga sem procedimento",
    "descricao": "Manobras de carga realizadas sem um planejamento adequado.",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Sem plano de rigging",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Movimentação de carga sem procedimento?"
    ],
    "condicaoDeNaoConformidade": "Sem plano de rigging",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Movimentação de carga sem procedimento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-02",
    "nr": "NR-11",
    "titulo": "Empilhadeira sem controle",
    "descricao": "Empilhadeira ou equipamento afim solto e sem rotina de manutenção preventiva.",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Sem manutenção empilhadeira",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Empilhadeira sem controle?"
    ],
    "condicaoDeNaoConformidade": "Sem manutenção empilhadeira",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Empilhadeira sem controle.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-03",
    "nr": "NR-11",
    "titulo": "Operador sem autorização",
    "descricao": "Operador de equipamento de movimentação de carga operando sem carteira ou autorização.",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Operador sem crachá/certificação",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Operador sem autorização?"
    ],
    "condicaoDeNaoConformidade": "Operador sem crachá/certificação",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Operador sem autorização.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-04",
    "nr": "NR-11",
    "titulo": "Armazenamento inadequado",
    "descricao": "Materiais perigosamente estocados em pilhas mal estruturadas (risco de queda).",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Pilha ou estrado irregular",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Armazenamento inadequado?"
    ],
    "condicaoDeNaoConformidade": "Pilha ou estrado irregular",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Armazenamento inadequado.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-05",
    "nr": "NR-11",
    "titulo": "Risco de queda de materiais",
    "descricao": "Identificado risco efetivo de queda de carga sobre as pessoas ou maquinário.",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Carga suspensa em rota de pessoas",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de queda de materiais?"
    ],
    "condicaoDeNaoConformidade": "Carga suspensa em rota de pessoas",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Risco de queda de materiais.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-06",
    "nr": "NR-11",
    "titulo": "Risco de esmagamento",
    "descricao": "Risco associado à aproximação excessiva de pessoas ao maquinário.",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Trabalhador próximo à carga",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de esmagamento?"
    ],
    "condicaoDeNaoConformidade": "Trabalhador próximo à carga",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Risco de esmagamento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-11-07",
    "nr": "NR-11",
    "titulo": "Risco de atropelamento",
    "descricao": "Falta demarcação separando vias de pedestres das vias dos veículos industriais.",
    "atividadeRelacionada": "Atividades mapeadas na NR-11",
    "perigo": "Cruzamento vias/pessoas",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de atropelamento?"
    ],
    "condicaoDeNaoConformidade": "Cruzamento vias/pessoas",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 18000,
    "chanceIncidenteBase": 85,
    "acaoRecomendada": "Este risco foi gerado com base na NR-11 porque foi identificado: Risco de atropelamento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-01",
    "nr": "NR-12",
    "titulo": "Máquina sem proteção",
    "descricao": "Sistema físico da máquina em uso não possui barreira ou anteparo projetado.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Sem barreira física",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Máquina sem proteção?"
    ],
    "condicaoDeNaoConformidade": "Sem barreira física",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Máquina sem proteção.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-02",
    "nr": "NR-12",
    "titulo": "Zona de risco acessível",
    "descricao": "Fácil acesso da mão ou parte do corpo à zona de ação das ferramentas cortantes.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Zona de risco exposta",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Zona de risco acessível?"
    ],
    "condicaoDeNaoConformidade": "Zona de risco exposta",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Zona de risco acessível.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-03",
    "nr": "NR-12",
    "titulo": "Ausência de dispositivo de parada",
    "descricao": "Ausência de botão de parada de emergência acessível ou cabo inoperante.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Sem parada de emergência",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de dispositivo de parada?"
    ],
    "condicaoDeNaoConformidade": "Sem parada de emergência",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Ausência de dispositivo de parada.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-04",
    "nr": "NR-12",
    "titulo": "Manutenção sem bloqueio",
    "descricao": "Manutenção sendo feita na máquina sem energia bloqueada e painel travado.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Manutenção com máquina ligada",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Manutenção sem bloqueio?"
    ],
    "condicaoDeNaoConformidade": "Manutenção com máquina ligada",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Manutenção sem bloqueio.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-05",
    "nr": "NR-12",
    "titulo": "Equipamento sem proteção coletiva",
    "descricao": "Máquina nova/layout reformado entrou em serviço sem proteções finalizadas.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Equipamento sem EPC",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Equipamento sem proteção coletiva?"
    ],
    "condicaoDeNaoConformidade": "Equipamento sem EPC",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Equipamento sem proteção coletiva.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-06",
    "nr": "NR-12",
    "titulo": "Risco de corte",
    "descricao": "Exposição efetiva a lâminas ou extremidades potentes que podem gerar amputação.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Lâmina desprotegida",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de corte?"
    ],
    "condicaoDeNaoConformidade": "Lâmina desprotegida",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Risco de corte.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-07",
    "nr": "NR-12",
    "titulo": "Risco de esmagamento",
    "descricao": "Partes móveis podem aprisionar partes do corpo devido à falta de sensor óptico.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Risco na prensa/eixo",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de esmagamento?"
    ],
    "condicaoDeNaoConformidade": "Risco na prensa/eixo",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Risco de esmagamento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-08",
    "nr": "NR-12",
    "titulo": "Risco de aprisionamento",
    "descricao": "Roupas largas ou colares próximos a rolimãs e fusos de giro.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Partes rotativas expostas",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de aprisionamento?"
    ],
    "condicaoDeNaoConformidade": "Partes rotativas expostas",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Risco de aprisionamento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-12-09",
    "nr": "NR-12",
    "titulo": "Risco de projeção",
    "descricao": "Material que está sendo usinado pela máquina corre risco de estilhaçar sem contenção.",
    "atividadeRelacionada": "Atividades mapeadas na NR-12",
    "perigo": "Sem anteparo de projeção",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de projeção?"
    ],
    "condicaoDeNaoConformidade": "Sem anteparo de projeção",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 35000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-12 porque foi identificado: Risco de projeção.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-17-01",
    "nr": "NR-17",
    "titulo": "Postura inadequada",
    "descricao": "Posto de trabalho forçando os colaboradores a adotarem posturas lesivas prolongadas.",
    "atividadeRelacionada": "Atividades mapeadas na NR-17",
    "perigo": "Móvel não anatômico",
    "tipoRisco": "Ergonômico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Postura inadequada?"
    ],
    "condicaoDeNaoConformidade": "Móvel não anatômico",
    "severidadeBase": "Média",
    "prioridadeBase": "Média",
    "prazoBase": 30,
    "multaBaseEstimativa": 6000,
    "chanceIncidenteBase": 60,
    "acaoRecomendada": "Este risco foi gerado com base na NR-17 porque foi identificado: Postura inadequada.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-17-02",
    "nr": "NR-17",
    "titulo": "Esforço repetitivo",
    "descricao": "Ritmo e tarefas que obrigam movimentos intensos, rápidos e imutáveis das mãos/pés.",
    "atividadeRelacionada": "Atividades mapeadas na NR-17",
    "perigo": "Falta de ginástica/pausa",
    "tipoRisco": "Ergonômico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Esforço repetitivo?"
    ],
    "condicaoDeNaoConformidade": "Falta de ginástica/pausa",
    "severidadeBase": "Média",
    "prioridadeBase": "Média",
    "prazoBase": 30,
    "multaBaseEstimativa": 6000,
    "chanceIncidenteBase": 60,
    "acaoRecomendada": "Este risco foi gerado com base na NR-17 porque foi identificado: Esforço repetitivo.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-17-03",
    "nr": "NR-17",
    "titulo": "Mobiliário inadequado",
    "descricao": "Bancos, mesas, displays de iluminação fora de especificação para tempo integral.",
    "atividadeRelacionada": "Atividades mapeadas na NR-17",
    "perigo": "Cadeira sem laudo ergonômico",
    "tipoRisco": "Ergonômico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Mobiliário inadequado?"
    ],
    "condicaoDeNaoConformidade": "Cadeira sem laudo ergonômico",
    "severidadeBase": "Média",
    "prioridadeBase": "Média",
    "prazoBase": 30,
    "multaBaseEstimativa": 6000,
    "chanceIncidenteBase": 60,
    "acaoRecomendada": "Este risco foi gerado com base na NR-17 porque foi identificado: Mobiliário inadequado.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-17-04",
    "nr": "NR-17",
    "titulo": "Levantamento manual de carga",
    "descricao": "Trabalhador carregando ou tracionando volumes que excedam a zona de segurança biomecânica.",
    "atividadeRelacionada": "Atividades mapeadas na NR-17",
    "perigo": "Carga pesada manual",
    "tipoRisco": "Ergonômico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Levantamento manual de carga?"
    ],
    "condicaoDeNaoConformidade": "Carga pesada manual",
    "severidadeBase": "Média",
    "prioridadeBase": "Média",
    "prazoBase": 30,
    "multaBaseEstimativa": 6000,
    "chanceIncidenteBase": 60,
    "acaoRecomendada": "Este risco foi gerado com base na NR-17 porque foi identificado: Levantamento manual de carga.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-17-05",
    "nr": "NR-17",
    "titulo": "Ritmo excessivo",
    "descricao": "Condições ou metas que forçam ritmos incompatíveis com a saúde ocupacional.",
    "atividadeRelacionada": "Atividades mapeadas na NR-17",
    "perigo": "Pressão de produção extrema",
    "tipoRisco": "Ergonômico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ritmo excessivo?"
    ],
    "condicaoDeNaoConformidade": "Pressão de produção extrema",
    "severidadeBase": "Média",
    "prioridadeBase": "Média",
    "prazoBase": 30,
    "multaBaseEstimativa": 6000,
    "chanceIncidenteBase": 60,
    "acaoRecomendada": "Este risco foi gerado com base na NR-17 porque foi identificado: Ritmo excessivo.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-17-06",
    "nr": "NR-17",
    "titulo": "Risco ergonômico sem avaliação",
    "descricao": "Ausência de Análise Ergonômica do Trabalho (AET) no posto examinado.",
    "atividadeRelacionada": "Atividades mapeadas na NR-17",
    "perigo": "Falta AET no setor",
    "tipoRisco": "Ergonômico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco ergonômico sem avaliação?"
    ],
    "condicaoDeNaoConformidade": "Falta AET no setor",
    "severidadeBase": "Média",
    "prioridadeBase": "Média",
    "prazoBase": 30,
    "multaBaseEstimativa": 6000,
    "chanceIncidenteBase": 60,
    "acaoRecomendada": "Este risco foi gerado com base na NR-17 porque foi identificado: Risco ergonômico sem avaliação.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-01",
    "nr": "NR-18",
    "titulo": "Ausência de proteção coletiva",
    "descricao": "Falta de proteção contra queda em canteiro (bandejas, guarda-corpos, redes).",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Periferia da laje desprotegida",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de proteção coletiva?"
    ],
    "condicaoDeNaoConformidade": "Periferia da laje desprotegida",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Ausência de proteção coletiva.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-02",
    "nr": "NR-18",
    "titulo": "Área sem isolamento",
    "descricao": "Canteiro de obras acessível a terceiros ou ausência de sinalização em fossos.",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Fosso exposto na obra",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Área sem isolamento?"
    ],
    "condicaoDeNaoConformidade": "Fosso exposto na obra",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Área sem isolamento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-03",
    "nr": "NR-18",
    "titulo": "Andaime irregular",
    "descricao": "Andaime montado fora de padrão técnico estrutural (sem travamento, sem rodapé).",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Andaime sem trava/rodapé",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Andaime irregular?"
    ],
    "condicaoDeNaoConformidade": "Andaime sem trava/rodapé",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Andaime irregular.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-04",
    "nr": "NR-18",
    "titulo": "Escavação sem controle",
    "descricao": "Trincheira com mais de 1,25m sem contenção das paredes para prevenir soterramento.",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Vala sem escoramento",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Escavação sem controle?"
    ],
    "condicaoDeNaoConformidade": "Vala sem escoramento",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Escavação sem controle.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-05",
    "nr": "NR-18",
    "titulo": "Queda de materiais",
    "descricao": "Equipamentos, restos de material sem amarração gerando risco aos trabalhadores na base.",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Trabalho sobreposto sem proteção",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Queda de materiais?"
    ],
    "condicaoDeNaoConformidade": "Trabalho sobreposto sem proteção",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Queda de materiais.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-06",
    "nr": "NR-18",
    "titulo": "Ausência de sinalização",
    "descricao": "Ausência ou deficiência generalizada das placas de segurança em fases de operação.",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Canteiro de obras desorientado",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de sinalização?"
    ],
    "condicaoDeNaoConformidade": "Canteiro de obras desorientado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Ausência de sinalização.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-18-07",
    "nr": "NR-18",
    "titulo": "Canteiro sem organização",
    "descricao": "Falta de limpeza e planejamento atrapalhando movimentação dos andaimes.",
    "atividadeRelacionada": "Atividades mapeadas na NR-18",
    "perigo": "Ordem e limpeza do canteiro deficientes",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Canteiro sem organização?"
    ],
    "condicaoDeNaoConformidade": "Ordem e limpeza do canteiro deficientes",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 1,
    "multaBaseEstimativa": 22000,
    "chanceIncidenteBase": 88,
    "acaoRecomendada": "Este risco foi gerado com base na NR-18 porque foi identificado: Canteiro sem organização.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-01",
    "nr": "NR-20",
    "titulo": "Armazenamento inadequado de inflamáveis",
    "descricao": "Estocagem de líquidos combustíveis ao ar livre ou local não apropriado (sem bacia, sem vent).",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Armazém químico inadequado",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Armazenamento inadequado de inflamáveis?"
    ],
    "condicaoDeNaoConformidade": "Armazém químico inadequado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Armazenamento inadequado de inflamáveis.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-02",
    "nr": "NR-20",
    "titulo": "Ausência de controle de fonte de ignição",
    "descricao": "Maçaricos, ferramentas de corte a quente ou estática elétrica ao lado de combustíveis.",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Fagulhas próximo a tanque",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de controle de fonte de ignição?"
    ],
    "condicaoDeNaoConformidade": "Fagulhas próximo a tanque",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Ausência de controle de fonte de ignição.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-03",
    "nr": "NR-20",
    "titulo": "Ausência de sinalização",
    "descricao": "Tanques de inflamáveis ou produtos corrosivos sem placa GHS, sem limites demarcados.",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Tanque não identificado",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de sinalização?"
    ],
    "condicaoDeNaoConformidade": "Tanque não identificado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Ausência de sinalização.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-04",
    "nr": "NR-20",
    "titulo": "Ausência de plano de emergência",
    "descricao": "Equipe não possui ou desconhece plano de atendimento a vazamento com fogo.",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Sem Brigada ou simulado NR-20",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de plano de emergência?"
    ],
    "condicaoDeNaoConformidade": "Sem Brigada ou simulado NR-20",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Ausência de plano de emergência.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-05",
    "nr": "NR-20",
    "titulo": "Risco de incêndio",
    "descricao": "Concentrações que possibilitam rápido perigo de incêndio a galpões principais.",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Risco iminente de propagação",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de incêndio?"
    ],
    "condicaoDeNaoConformidade": "Risco iminente de propagação",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Risco de incêndio.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-06",
    "nr": "NR-20",
    "titulo": "Risco de explosão",
    "descricao": "Mistura em proporções estequiométricas perigosas e falta de ventilação exaustora.",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Atmosfera LEL crítica",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de explosão?"
    ],
    "condicaoDeNaoConformidade": "Atmosfera LEL crítica",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Risco de explosão.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-20-07",
    "nr": "NR-20",
    "titulo": "Manipulação sem procedimento",
    "descricao": "Trabalhadores trocando recipientes de solventes ou tinturaria sem luvas e aterramento.",
    "atividadeRelacionada": "Atividades mapeadas na NR-20",
    "perigo": "Transvase irregular de vasilhame",
    "tipoRisco": "Incêndio/Explosão",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Manipulação sem procedimento?"
    ],
    "condicaoDeNaoConformidade": "Transvase irregular de vasilhame",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 50000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-20 porque foi identificado: Manipulação sem procedimento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-01",
    "nr": "NR-23",
    "titulo": "Extintor vencido",
    "descricao": "Sistemas portáteis de combate estão sem manutenção.",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Extintor despressurizado",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Extintor vencido?"
    ],
    "condicaoDeNaoConformidade": "Extintor despressurizado",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Extintor vencido.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-02",
    "nr": "NR-23",
    "titulo": "Extintor obstruído",
    "descricao": "Cargas, móveis e outros objetos depositados exatamente abaixo e em volta das placas de extintores.",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Extintor bloqueado",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Extintor obstruído?"
    ],
    "condicaoDeNaoConformidade": "Extintor bloqueado",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Extintor obstruído.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-03",
    "nr": "NR-23",
    "titulo": "Rota de fuga obstruída",
    "descricao": "Acesso direto à porta de emergência trancado ou com passagem travada.",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Rota de fuga parada",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Rota de fuga obstruída?"
    ],
    "condicaoDeNaoConformidade": "Rota de fuga parada",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Rota de fuga obstruída.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-04",
    "nr": "NR-23",
    "titulo": "Ausência de sinalização de emergência",
    "descricao": "Corredores não possuem iluminação complementar, setas e luminosos de aviso.",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Placas fotoluminescentes ausentes",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de sinalização de emergência?"
    ],
    "condicaoDeNaoConformidade": "Placas fotoluminescentes ausentes",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Ausência de sinalização de emergência.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-05",
    "nr": "NR-23",
    "titulo": "Ausência de treinamento de abandono",
    "descricao": "Local não fez simulação anual como previsto na literatura técnica de brigadas (IT).",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Sem simulado na unidade",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de treinamento de abandono?"
    ],
    "condicaoDeNaoConformidade": "Sem simulado na unidade",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Ausência de treinamento de abandono.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-06",
    "nr": "NR-23",
    "titulo": "Alarme indisponível",
    "descricao": "Acionadores manuais de alarme ou detectores não funcionam ao teste.",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Botoeira de incêndio inoperante",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Alarme indisponível?"
    ],
    "condicaoDeNaoConformidade": "Botoeira de incêndio inoperante",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Alarme indisponível.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-23-07",
    "nr": "NR-23",
    "titulo": "Equipamento de emergência indisponível",
    "descricao": "Ausência de mangueiras, esguichos, ou bomba elétrica desativada em caso de pânico.",
    "atividadeRelacionada": "Atividades mapeadas na NR-23",
    "perigo": "Hidrante desequipado",
    "tipoRisco": "Acidente/Incêndio",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Equipamento de emergência indisponível?"
    ],
    "condicaoDeNaoConformidade": "Hidrante desequipado",
    "severidadeBase": "Alta",
    "prioridadeBase": "Alta",
    "prazoBase": 2,
    "multaBaseEstimativa": 15000,
    "chanceIncidenteBase": 80,
    "acaoRecomendada": "Este risco foi gerado com base na NR-23 porque foi identificado: Equipamento de emergência indisponível.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-26-01",
    "nr": "NR-26",
    "titulo": "Produto sem identificação",
    "descricao": "Galões e potes estocados nas áreas contendo substâncias sem placa de nome ou rotulagem original.",
    "atividadeRelacionada": "Atividades mapeadas na NR-26",
    "perigo": "Galão sem rótulo ativo",
    "tipoRisco": "Químico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Produto sem identificação?"
    ],
    "condicaoDeNaoConformidade": "Galão sem rótulo ativo",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 10,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 70,
    "acaoRecomendada": "Este risco foi gerado com base na NR-26 porque foi identificado: Produto sem identificação.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-26-02",
    "nr": "NR-26",
    "titulo": "Ausência de rotulagem",
    "descricao": "Ausência clara e manifesta de pictograma que detalham e avisam do poder nocivo do item.",
    "atividadeRelacionada": "Atividades mapeadas na NR-26",
    "perigo": "Risco GHS ausente no rótulo",
    "tipoRisco": "Químico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de rotulagem?"
    ],
    "condicaoDeNaoConformidade": "Risco GHS ausente no rótulo",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 10,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 70,
    "acaoRecomendada": "Este risco foi gerado com base na NR-26 porque foi identificado: Ausência de rotulagem.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-26-03",
    "nr": "NR-26",
    "titulo": "Ausência de FISPQ/FDS",
    "descricao": "A empresa comprou compostos novos sem o arquivo que guia como proceder na inalação.",
    "atividadeRelacionada": "Atividades mapeadas na NR-26",
    "perigo": "FDS indisponível",
    "tipoRisco": "Químico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de FISPQ/FDS?"
    ],
    "condicaoDeNaoConformidade": "FDS indisponível",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 10,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 70,
    "acaoRecomendada": "Este risco foi gerado com base na NR-26 porque foi identificado: Ausência de FISPQ/FDS.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-26-04",
    "nr": "NR-26",
    "titulo": "Sinalização inadequada",
    "descricao": "Pisos não estão pintados demonstrando passagem, perigo ou corrimões.",
    "atividadeRelacionada": "Atividades mapeadas na NR-26",
    "perigo": "Linha de pedestre apagada",
    "tipoRisco": "Químico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Sinalização inadequada?"
    ],
    "condicaoDeNaoConformidade": "Linha de pedestre apagada",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 10,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 70,
    "acaoRecomendada": "Este risco foi gerado com base na NR-26 porque foi identificado: Sinalização inadequada.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-26-05",
    "nr": "NR-26",
    "titulo": "Armazenamento químico inadequado",
    "descricao": "Produtos com PH reativo incompatível estocados no mesmo dique e estrado (ex: oxidantes e orgânicos, soda e oxidantes ácidos fortes).",
    "atividadeRelacionada": "Atividades mapeadas na NR-26",
    "perigo": "Armazenagem incompatível",
    "tipoRisco": "Químico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Armazenamento químico inadequado?"
    ],
    "condicaoDeNaoConformidade": "Armazenagem incompatível",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 10,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 70,
    "acaoRecomendada": "Este risco foi gerado com base na NR-26 porque foi identificado: Armazenamento químico inadequado.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-26-06",
    "nr": "NR-26",
    "titulo": "Risco de exposição química",
    "descricao": "Manipulação do agente com névoa alta resultando em imediata contaminação percutânea.",
    "atividadeRelacionada": "Atividades mapeadas na NR-26",
    "perigo": "Respingos e aerossol visível sem contenção",
    "tipoRisco": "Químico",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de exposição química?"
    ],
    "condicaoDeNaoConformidade": "Respingos e aerossol visível sem contenção",
    "severidadeBase": "Média",
    "prioridadeBase": "Alta",
    "prazoBase": 10,
    "multaBaseEstimativa": 12000,
    "chanceIncidenteBase": 70,
    "acaoRecomendada": "Este risco foi gerado com base na NR-26 porque foi identificado: Risco de exposição química.",
    "bloqueante": false,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-01",
    "nr": "NR-33",
    "titulo": "Entrada sem permissão",
    "descricao": "Ingresso de operador sem formulário oficial de liberação PET (Permissão e Entrada Temporária).",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Trabalho em silo s/PET",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Entrada sem permissão?"
    ],
    "condicaoDeNaoConformidade": "Trabalho em silo s/PET",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Entrada sem permissão.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-02",
    "nr": "NR-33",
    "titulo": "Ausência de vigia",
    "descricao": "Funcionário sozinho em tanque, cisterna sem um par de olhos oficial do lado de fora.",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Sem vigia no bocal",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de vigia?"
    ],
    "condicaoDeNaoConformidade": "Sem vigia no bocal",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Ausência de vigia.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-03",
    "nr": "NR-33",
    "titulo": "Ausência de medição atmosférica",
    "descricao": "Entrada de manutenção procedida sem verificação explosiva/oxigênio do equipamento O2, H2S.",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Sem multimedidor no poço",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de medição atmosférica?"
    ],
    "condicaoDeNaoConformidade": "Sem multimedidor no poço",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Ausência de medição atmosférica.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-04",
    "nr": "NR-33",
    "titulo": "Ausência de plano de resgate",
    "descricao": "Tripé ou guincho de resgate não está montado se for preciso puxar desmaiado na urgência.",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Sem guincho/preparo salva-vidas",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de plano de resgate?"
    ],
    "condicaoDeNaoConformidade": "Sem guincho/preparo salva-vidas",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Ausência de plano de resgate.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-05",
    "nr": "NR-33",
    "titulo": "Trabalhador sem capacitação",
    "descricao": "O certificado de 40h e sua renovação encontram-se expirados pela auditoria.",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Sem treinamento NR-33 prático",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Trabalhador sem capacitação?"
    ],
    "condicaoDeNaoConformidade": "Sem treinamento NR-33 prático",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Trabalhador sem capacitação.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-06",
    "nr": "NR-33",
    "titulo": "Ventilação inadequada",
    "descricao": "Sistema não consegue manter circulação de renovação exigindo o uso imediato (exaustor parado).",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Exaustor/Insuflador parado",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ventilação inadequada?"
    ],
    "condicaoDeNaoConformidade": "Exaustor/Insuflador parado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Ventilação inadequada.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-07",
    "nr": "NR-33",
    "titulo": "Risco de asfixia",
    "descricao": "Insuflamento da carga não elimina bolso de H2S provocando provável parada cardiáca no pulmão.",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "O2 abaixo de 19,5%",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de asfixia?"
    ],
    "condicaoDeNaoConformidade": "O2 abaixo de 19,5%",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Risco de asfixia.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-08",
    "nr": "NR-33",
    "titulo": "Risco de intoxicação",
    "descricao": "Permanência longa inalando gases da solda na galeria (fumos metálicos).",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Sem máscara insuflada com exaustão",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de intoxicação?"
    ],
    "condicaoDeNaoConformidade": "Sem máscara insuflada com exaustão",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Risco de intoxicação.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-33-09",
    "nr": "NR-33",
    "titulo": "Atmosfera perigosa",
    "descricao": "Gás com poder atômico explosivo medido acima de 10% LEL, tornando entrada impossível/mortal.",
    "atividadeRelacionada": "Atividades mapeadas na NR-33",
    "perigo": "Limite LEL explosividade superado",
    "tipoRisco": "Acidente/Resgate",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Atmosfera perigosa?"
    ],
    "condicaoDeNaoConformidade": "Limite LEL explosividade superado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 45000,
    "chanceIncidenteBase": 95,
    "acaoRecomendada": "Este risco foi gerado com base na NR-33 porque foi identificado: Atmosfera perigosa.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-01",
    "nr": "NR-35",
    "titulo": "Ausência de linha de vida",
    "descricao": "Acesso elevado e transição no telhado não dispõe de linha de vida fixa ou provisória homologada.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Telhado/Plataforma sem linha de vida",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de linha de vida?"
    ],
    "condicaoDeNaoConformidade": "Telhado/Plataforma sem linha de vida",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Ausência de linha de vida.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-02",
    "nr": "NR-35",
    "titulo": "Ausência de ponto de ancoragem",
    "descricao": "Os furos e ancoradouros de espera não aguentam torque, não havendo verificação de engenheiro mecânico.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Ponto de ancoragem inseguro",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de ponto de ancoragem?"
    ],
    "condicaoDeNaoConformidade": "Ponto de ancoragem inseguro",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Ausência de ponto de ancoragem.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-03",
    "nr": "NR-35",
    "titulo": "Ausência de cinto/trava-quedas",
    "descricao": "EPI primordial (cinto abdominal e talabarte duplo) omitido pelos envolvidos no percurso.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Sem cinto/trava-quedas operando",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de cinto/trava-quedas?"
    ],
    "condicaoDeNaoConformidade": "Sem cinto/trava-quedas operando",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Ausência de cinto/trava-quedas.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-04",
    "nr": "NR-35",
    "titulo": "Ausência de isolamento da área inferior",
    "descricao": "Risco fatal aos terceiros pelo trânsito indiscriminado abaixo de peças suspensas.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Isolamento solo ignorado",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de isolamento da área inferior?"
    ],
    "condicaoDeNaoConformidade": "Isolamento solo ignorado",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Ausência de isolamento da área inferior.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-05",
    "nr": "NR-35",
    "titulo": "Trabalhador sem capacitação",
    "descricao": "Desconhecimento grave das noções como Fator de queda e corda em atrito que mata os técnicos.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Sem certificado NR-35 oficial",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Trabalhador sem capacitação?"
    ],
    "condicaoDeNaoConformidade": "Sem certificado NR-35 oficial",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Trabalhador sem capacitação.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-06",
    "nr": "NR-35",
    "titulo": "Ausência de permissão/procedimento",
    "descricao": "A Permissão (PT) não foi feita pelo TST garantindo que todos os riscos visuais estão zerados.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Sem PT Trabalho em Altura validada",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Ausência de permissão/procedimento?"
    ],
    "condicaoDeNaoConformidade": "Sem PT Trabalho em Altura validada",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Ausência de permissão/procedimento.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-07",
    "nr": "NR-35",
    "titulo": "Risco de queda de altura",
    "descricao": "Beira aberta de poço/fosso ou passarela danificada em telha translúcida (acidente gravíssimo).",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Próximo à borda sem amarração",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de queda de altura?"
    ],
    "condicaoDeNaoConformidade": "Próximo à borda sem amarração",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Risco de queda de altura.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  },
  {
    "id": "nr-35-08",
    "nr": "NR-35",
    "titulo": "Risco de queda de materiais",
    "descricao": "Operação usando ferramentas soltas e parafusos grandes no parapeito superior que podem golpear capacetes no subsolo.",
    "atividadeRelacionada": "Atividades mapeadas na NR-35",
    "perigo": "Ferramenta sem amarra",
    "tipoRisco": "Acidente",
    "perguntasChecklist": [
      "Houve irregularidade referente a: Risco de queda de materiais?"
    ],
    "condicaoDeNaoConformidade": "Ferramenta sem amarra",
    "severidadeBase": "Crítica",
    "prioridadeBase": "Urgente",
    "prazoBase": 0,
    "multaBaseEstimativa": 30000,
    "chanceIncidenteBase": 90,
    "acaoRecomendada": "Este risco foi gerado com base na NR-35 porque foi identificado: Risco de queda de materiais.",
    "bloqueante": true,
    "geraRisco": true,
    "geraAcao": true,
    "impactaScore": true,
    "regraFixa": true,
    "editavel": false,
    "removivel": false,
    "fonte": "Regra fixa do motor ApexShield"
  }
];

export function normalizarRegra(regra: any) {
  return {
    id: regra.id,
    nr: regra.nr || '',
    titulo: regra.titulo || regra.name || 'Nova Regra',
    descricao: regra.descricao || '',
    severidadeBase: regra.severidadeBase || regra.severity || 'Médio',
    prioridadeBase: regra.prioridadeBase || 'Média',
    prazoBase: regra.prazoBase || 7,
    multaBaseEstimativa: regra.multaBaseEstimativa || regra.multaEstimada || 0,
    chanceIncidenteBase: regra.chanceIncidenteBase || regra.chance || 0,
    acaoRecomendada: regra.acaoRecomendada || regra.autoAction || 'Revisar conformidade',
    impactaScore: regra.impactaScore !== undefined ? regra.impactaScore : true,
    regraFixa: regra.regraFixa || false,
    editavel: regra.editavel !== undefined ? regra.editavel : true,
    removivel: regra.removivel !== undefined ? regra.removivel : true,
    ...regra
  };
}

export function getTodasRegrasAtivas(customRules: any[]) {
  const normCustom = (customRules || []).map(r => normalizarRegra(r));
  const normFixed = fixedNrRules.map(r => normalizarRegra(r));
  
  const fixedIds = new Set(normFixed.map(r => r.id));
  const filteredCustom = normCustom.filter(r => !fixedIds.has(r.id));

  return [...filteredCustom, ...normFixed];
}

export function isFixedRule(rule: any): boolean {
  return rule?.regraFixa === true;
}

export function canEditRule(rule: any): boolean {
  return rule?.regraFixa !== true && rule?.editavel === true;
}

export function canRemoveRule(rule: any): boolean {
  return rule?.regraFixa !== true && rule?.removivel === true;
}

