import { RiskRule } from './types';

export const INITIAL_RISK_RULES: RiskRule[] = [
  // --- BASE SST ---
  // NR-06
  {
    id: 'rr-sst-nr06-01',
    titulo: 'EPI obrigatório ausente',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral', 'Operacional'],
    nrRelacionada: 'NR-06',
    criticidade: 'Crítico',
    condicao: 'EPI não encontrado ou não disponível para o trabalhador',
    acaoSugerida: 'Providenciar o fornecimento imediato do EPI e registrar a entrega.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.300 - R$ 6.300'
  },
  {
    id: 'rr-sst-nr06-02',
    titulo: 'EPI sem evidência de entrega/controle',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral'],
    nrRelacionada: 'NR-06',
    criticidade: 'Alto',
    condicao: 'Ausência de ficha de EPI ou registro digital de entrega',
    acaoSugerida: 'Regularizar os registros de entrega e controle de EPIs imediamente.',
    prazoPadraoHoras: 24,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 1.800 - R$ 4.500'
  },
  {
    id: 'rr-sst-nr06-03',
    titulo: 'Uso inadequado de EPI',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral'],
    nrRelacionada: 'NR-06',
    criticidade: 'Alto',
    condicao: 'Trabalhador utiliza o EPI de forma incorreta ou o EPI está danificado',
    acaoSugerida: 'Treinar o trabalhador sobre o uso correto e substituir o EPI se necessário.',
    prazoPadraoHoras: 8,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.100 - R$ 5.200'
  },
  // NR-17
  {
    id: 'rr-sst-nr17-01',
    titulo: 'Posto de trabalho com indício ergonômico inadequado',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral', 'Administrativo'],
    nrRelacionada: 'NR-17',
    criticidade: 'Médio',
    condicao: 'Mobiliário ou equipamentos em desacordo com a AEP/AET',
    acaoSugerida: 'Ajustar o posto de trabalho conforme recomendações ergonômicas.',
    prazoPadraoHoras: 72,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 1.200 - R$ 3.800'
  },
  {
    id: 'rr-sst-nr17-02',
    titulo: 'Atividade repetitiva sem controle operacional',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Operacional', 'Linha de Produção'],
    nrRelacionada: 'NR-17',
    criticidade: 'Alto',
    condicao: 'Ciclos de trabalho curtos e repetitivos sem pausas regulamentares',
    acaoSugerida: 'Implementar rodízio de tarefas e pausas obrigatórias.',
    prazoPadraoHoras: 48,
    exigeEvidencia: false,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 3.000 - R$ 7.500'
  },
  // NR-23
  {
    id: 'rr-sst-nr23-01',
    titulo: 'Extintor ausente, vencido ou obstruído',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral'],
    nrRelacionada: 'NR-23',
    criticidade: 'Crítico',
    condicao: 'Equipamento de combate a incêndio sem condições de uso',
    acaoSugerida: 'Recarregar, desobstruir or instalar novos extintores imediatamente.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.500 - R$ 8.000'
  },
  {
    id: 'rr-sst-nr23-02',
    titulo: 'Rota de fuga obstruída',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral'],
    nrRelacionada: 'NR-23',
    criticidade: 'Crítico',
    condicao: 'Objetos bloqueando corredores ou portas de emergência',
    acaoSugerida: 'Liberar as rotas de fuga e sinalizar adequadamente.',
    prazoPadraoHoras: 2,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 4.000 - R$ 12.000'
  },
  // NR-24
  {
    id: 'rr-sst-nr24-01',
    titulo: 'Condição sanitária/conforto inadequada',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral'],
    nrRelacionada: 'NR-24',
    criticidade: 'Médio',
    condicao: 'Sanitários ou refeitórios em condições precárias de higiene ou conservação',
    acaoSugerida: 'Realizar manutenção e limpeza profunda das instalações.',
    prazoPadraoHoras: 24,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 1.500 - R$ 4.000'
  },
  // NR-26
  {
    id: 'rr-sst-nr26-01',
    titulo: 'Área de risco sem sinalização',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral', 'Operacional'],
    nrRelacionada: 'NR-26',
    criticidade: 'Alto',
    condicao: 'Falta de placas de advertência em locais perigosos',
    acaoSugerida: 'Instalar sinalização de segurança visível e padronizada.',
    prazoPadraoHoras: 24,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 1.200 - R$ 3.500'
  },
  {
    id: 'rr-sst-nr26-02',
    titulo: 'Produto químico sem identificação',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Geral', 'Limpeza'],
    nrRelacionada: 'NR-26',
    criticidade: 'Alto',
    condicao: 'Frascos ou recipientes com produtos químicos sem rótulo',
    acaoSugerida: 'Identificar todos os produtos conforme padrão GHS.',
    prazoPadraoHoras: 12,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.000 - R$ 5.500'
  },
  // NR-01
  {
    id: 'rr-sst-nr01-01',
    titulo: 'Risco sem responsável',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Gestão SST'],
    nrRelacionada: 'NR-01',
    criticidade: 'Alto',
    condicao: 'Risco identificado no inventário sem atribuição de responsável',
    acaoSugerida: 'Designar um responsável técnico pela gestão deste risco.',
    prazoPadraoHoras: 48,
    exigeEvidencia: false,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 1.000 - R$ 3.000'
  },
  {
    id: 'rr-sst-nr01-02',
    titulo: 'Não conformidade sem evidência',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Gestão SST'],
    nrRelacionada: 'NR-01',
    criticidade: 'Médio',
    condicao: 'Apontamentos técnicos sem registros comprobatórios (fotos/docs)',
    acaoSugerida: 'Anexar evidências para todas as fragilidades apontadas.',
    prazoPadraoHoras: 72,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: false,
    faixaMultaPadrao: '-'
  },
  {
    id: 'rr-sst-nr01-03',
    titulo: 'Ação corretiva vencida',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Gestão SST'],
    nrRelacionada: 'NR-01',
    criticidade: 'Alto',
    condicao: 'Prazos do plano de ação ultrapassados sem conclusão',
    acaoSugerida: 'Concluir a ação ou justificar novo prazo com medidas mitigadoras.',
    prazoPadraoHoras: 24,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 3.000 - R$ 9.000'
  },
  {
    id: 'rr-sst-nr01-04',
    titulo: 'Risco crítico sem tratativa',
    pacote: 'Base SST',
    segmentos: ['Todos'],
    atividades: ['Gestão SST'],
    nrRelacionada: 'NR-01',
    criticidade: 'Crítico',
    condicao: 'Risco de nível crítico sem medidas de controle imediatas',
    acaoSugerida: 'Interromper atividade se necessário e aplicar controle imediato.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 5.000 - R$ 15.000'
  },

  // --- CONSTRUÇÃO CIVIL ---
  // NR-18
  {
    id: 'rr-con-nr18-01',
    titulo: 'Andaime sem proteção adequada',
    pacote: 'Construção Civil',
    segmentos: ['Construção Civil'],
    atividades: ['Trabalho em altura', 'Obras'],
    nrRelacionada: 'NR-18',
    criticidade: 'Crítico',
    condicao: 'Andaime sem guarda-corpo, rodapé ou forração completa',
    acaoSugerida: 'Interditar o uso do andaime até a adequação completa.',
    prazoPadraoHoras: 8,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 4.000 - R$ 15.000'
  },
  {
    id: 'rr-con-nr18-02',
    titulo: 'Escavação sem isolamento/sinalização',
    pacote: 'Construção Civil',
    segmentos: ['Construção Civil'],
    atividades: ['Obras', 'Escavação'],
    nrRelacionada: 'NR-18',
    criticidade: 'Crítico',
    condicao: 'Bordas de escavação desprotegidas e sem sinalização de advertência',
    acaoSugerida: 'Isolar a área com barreiras físicas e sinalizar riscos.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 3.500 - R$ 10.000'
  },
  {
    id: 'rr-con-nr18-03',
    titulo: 'Área de obra sem isolamento',
    pacote: 'Construção Civil',
    segmentos: ['Construção Civil'],
    atividades: ['Obras'],
    nrRelacionada: 'NR-18',
    criticidade: 'Alto',
    condicao: 'Canteiro aberto sem controle de acesso de terceiros',
    acaoSugerida: 'Fechar o perímetro da obra e controlar acessos.',
    prazoPadraoHoras: 24,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.000 - R$ 6.000'
  },
  {
    id: 'rr-con-nr18-04',
    titulo: 'Queda de materiais sem controle',
    pacote: 'Construção Civil',
    segmentos: ['Construção Civil'],
    atividades: ['Obras'],
    nrRelacionada: 'NR-18',
    criticidade: 'Crítico',
    condicao: 'Ausência de telas, plataformas ou redes de proteção',
    acaoSugerida: 'Instalar proteções coletivas contra queda de objetos.',
    prazoPadraoHoras: 12,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 5.000 - R$ 20.000'
  },
  // NR-35
  {
    id: 'rr-con-nr35-01',
    titulo: 'Trabalho em altura sem treinamento válido',
    pacote: 'Construção Civil',
    segmentos: ['Todos'],
    atividades: ['Trabalho em altura'],
    nrRelacionada: 'NR-35',
    criticidade: 'Crítico',
    condicao: 'Colaborador realizando atividade em altura com certificado vencido',
    acaoSugerida: 'Suspender atividade e realizar treinamento de reciclagem.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 3.000 - R$ 10.000'
  },
  {
    id: 'rr-con-nr35-02',
    titulo: 'Trabalho em altura sem sistema de proteção',
    pacote: 'Construção Civil',
    segmentos: ['Todos'],
    atividades: ['Trabalho em altura'],
    nrRelacionada: 'NR-35',
    criticidade: 'Crítico',
    condicao: 'Uso de talabarte sem ancoragem ou linha de vida inadequada',
    acaoSugerida: 'Adesão imediata ao sistema de ancoragem certificado.',
    prazoPadraoHoras: 1,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 6.000 - R$ 25.000'
  },
  {
    id: 'rr-con-nr35-03',
    titulo: 'Ausência de evidência para atividade em altura',
    pacote: 'Construção Civil',
    segmentos: ['Todos'],
    atividades: ['Trabalho em altura'],
    nrRelacionada: 'NR-35',
    criticidade: 'Alto',
    condicao: 'Atividade iniciada sem a devida Permissão de Trabalho (PT)',
    acaoSugerida: 'Paralisar atividade e emitir PT with análise de risco.',
    prazoPadraoHoras: 2,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.500 - R$ 8.000'
  },
  // NR-33
  {
    id: 'rr-con-nr33-01',
    titulo: 'Espaço confinado sem autorização/evidência',
    pacote: 'Construção Civil',
    segmentos: ['Todos'],
    atividades: ['Espaço Confinado'],
    nrRelacionada: 'NR-33',
    criticidade: 'Crítico',
    condicao: 'Entrada realizada sem PET ou sem vigia presente',
    acaoSugerida: 'Retirar equipe, emitir PET e posicionar vigia treinado.',
    prazoPadraoHoras: 1,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 8.000 - R$ 30.000'
  },
  // NR-10 (Const)
  {
    id: 'rr-con-nr10-01',
    titulo: 'Instalação elétrica temporária irregular',
    pacote: 'Construção Civil',
    segmentos: ['Construção Civil'],
    atividades: ['Eletricidade', 'Obras'],
    nrRelacionada: 'NR-10',
    criticidade: 'Crítico',
    condicao: 'Fiação exposta, gambiarras ou quadros sem proteção contra contato',
    acaoSugerida: 'Refazer instalação por eletricista habilitado.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 4.000 - R$ 15.000'
  },

  // --- INDÚSTRIA ---
  // NR-12
  {
    id: 'rr-ind-nr12-01',
    titulo: 'Máquina sem proteção adequada',
    pacote: 'Indústria',
    segmentos: ['Indústria'],
    atividades: ['Operação de Máquinas'],
    nrRelacionada: 'NR-12',
    criticidade: 'Crítico',
    condicao: 'Engrenagens, polias ou partes móveis sem proteção fixa ou móvel intertravada',
    acaoSugerida: 'Interditar máquina e instalar proteções de acordo com apreciação de riscos.',
    prazoPadraoHoras: 12,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 5.000 - R$ 25.000'
  },
  {
    id: 'rr-ind-nr12-02',
    titulo: 'Dispositivo de segurança ausente/inoperante',
    pacote: 'Indústria',
    segmentos: ['Indústria'],
    atividades: ['Operação de Máquinas'],
    nrRelacionada: 'NR-12',
    criticidade: 'Crítico',
    condicao: 'Botão de emergência ou cortina de luz burlados ou quebrados',
    acaoSugerida: 'Substituir dispositivo de segurança imediatamente.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 6.000 - R$ 18.000'
  },
  // NR-10 (Ind)
  {
    id: 'rr-ind-nr10-01',
    titulo: 'Manutenção sem bloqueio/etiquetagem',
    pacote: 'Indústria',
    segmentos: ['Indústria'],
    atividades: ['Manutenção', 'Eletricidade'],
    nrRelacionada: 'NR-10',
    criticidade: 'Crítico',
    condicao: 'Intervenção em máquina energizada sem cadeado de bloqueio LOTO',
    acaoSugerida: 'Paralisar e aplicar procedimento de bloqueio de energia.',
    prazoPadraoHoras: 1,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 7.000 - R$ 20.000'
  },
  // NR-11
  {
    id: 'rr-ind-nr11-01',
    titulo: 'Movimentação de carga sem controle',
    pacote: 'Indústria',
    segmentos: ['Indústria', 'Logística'],
    atividades: ['Logística', 'Movimentação de Carga'],
    nrRelacionada: 'NR-11',
    criticidade: 'Alto',
    condicao: 'Operação de içamento sem isolamento de área ou plano de rigging',
    acaoSugerida: 'Isolar raio de queda da carga e validar procedimentos.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 3.500 - R$ 12.000'
  },
  // NR-15
  {
    id: 'rr-ind-nr15-01',
    titulo: 'Exposição a ruído/calor/agente sem controle registrado',
    pacote: 'Indústria',
    segmentos: ['Indústria'],
    atividades: ['Operacional'],
    nrRelacionada: 'NR-15',
    criticidade: 'Alto',
    condicao: 'Agente insalubre acima do limite sem EPC/EPI eficaz comprovado',
    acaoSugerida: 'Realizar medição técnica e implementar controle de engenharia.',
    prazoPadraoHoras: 72,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 4.000 - R$ 15.000'
  },
  // NR-20
  {
    id: 'rr-ind-nr20-01',
    titulo: 'Inflamável armazenado/manuseado sem controle adequado',
    pacote: 'Indústria',
    segmentos: ['Indústria', 'Química'],
    atividades: ['Inflamáveis'],
    nrRelacionada: 'NR-20',
    criticidade: 'Crítico',
    condicao: 'Vazamentos ou estocagem fora de local ventilado/aterrado',
    acaoSugerida: 'Conter vazamento e regularizar armazenamento técnico.',
    prazoPadraoHoras: 8,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 5.000 - R$ 25.000'
  },

  // --- SAÚDE/HOSPITALAR ---
  // NR-32
  {
    id: 'rr-sau-nr32-01',
    titulo: 'Perfurocortante descartado inadequadamente',
    pacote: 'Saúde/Hospitalar',
    segmentos: ['Saúde', 'Hospitalar'],
    atividades: ['Atendimento em Saúde', 'Resíduos'],
    nrRelacionada: 'NR-32',
    criticidade: 'Crítico',
    condicao: 'Agulhas em lixo comum ou coletores superlotados (acima de 2/3)',
    acaoSugerida: 'Substituir coletor e realizar descarte em lixo infectante.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 4.500 - R$ 18.000'
  },
  {
    id: 'rr-sau-nr32-02',
    titulo: 'Risco biológico sem EPI adequado',
    pacote: 'Saúde/Hospitalar',
    segmentos: ['Saúde', 'Hospitalar'],
    atividades: ['Atendimento em Saúde'],
    nrRelacionada: 'NR-32',
    criticidade: 'Crítico',
    condicao: 'Trabalhador em área de isolamento sem máscara N95 ou avental impermeável',
    acaoSugerida: 'Interromper atendimento até a paramentação completa.',
    prazoPadraoHoras: 1,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 3.000 - R$ 12.000'
  },
  {
    id: 'rr-sau-nr32-03',
    titulo: 'Resíduo de saúde armazenado incorretamente',
    pacote: 'Saúde/Hospitalar',
    segmentos: ['Saúde', 'Hospitalar'],
    atividades: ['Resíduos'],
    nrRelacionada: 'NR-32',
    criticidade: 'Alto',
    condicao: 'Sacos de lixo infectante fora do abrigo temporário ou sem identificação',
    acaoSugerida: 'Recolher resíduos para área técnica sinalizada.',
    prazoPadraoHoras: 12,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.500 - R$ 8.000'
  },
  // NR-06 (Saúde)
  {
    id: 'rr-sau-nr06-01',
    titulo: 'EPI hospitalar ausente ou inadequado',
    pacote: 'Saúde/Hospitalar',
    segmentos: ['Saúde', 'Hospitalar'],
    atividades: ['Atendimento em Saúde'],
    nrRelacionada: 'NR-06',
    criticidade: 'Alto',
    condicao: 'Luvas de procedimento com furos ou máscaras cirúrgicas reutilizadas',
    acaoSugerida: 'Descartar material danificado e repor estoque.',
    prazoPadraoHoras: 4,
    exigeEvidencia: true,
    ativo: true,
    geraMultaEstimativa: true,
    faixaMultaPadrao: 'R$ 2.000 - R$ 7.000'
  }
];
