/**
 * Checklist rule catalog for the JavaScript normative engine.
 */

export const NR_ACTIVITY_TO_NRS = {
  "uso-de-epi": ["NR-06"],
  "trabalho-em-altura": ["NR-35", "NR-06"],
  "espaco-confinado": ["NR-33", "NR-06"],
  eletricidade: ["NR-10", "NR-06"],
  "maquina-sem-protecao": ["NR-12", "NR-06"],
  "movimentacao-de-carga": ["NR-11", "NR-06"],
  inflamaveis: ["NR-20", "NR-23", "NR-06"],
  sinalizacao: ["NR-26"],
  ergonomia: ["NR-17"],
  "emergencia-incendio": ["NR-23"],
  "construcao-civil": ["NR-18", "NR-35", "NR-06"],
};

export const NR_RULES = [
  {
    id: "RULE-NR06-EPI-001",
    nr: "NR-06",
    atividadeRelacionada: "uso-de-epi",
    perguntaChecklist: "Os trabalhadores estao utilizando os EPIs obrigatorios?",
    titulo: "Uso obrigatorio de EPI",
    descricao: "Falta de uso adequado de EPI em atividade exposta.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Alta",
    prioridadeSugerida: "Alta",
    prazoSugeridoDias: 3,
    acaoRecomendada: "Interromper a atividade ate regularizar o uso de EPI.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR35-ALT-001",
    nr: "NR-35",
    atividadeRelacionada: "trabalho-em-altura",
    perguntaChecklist: "Existe analise de risco para o trabalho em altura?",
    titulo: "Analise de risco em altura",
    descricao: "Atividade em altura sem analise de risco valida.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Crítica",
    prioridadeSugerida: "Crítica",
    prazoSugeridoDias: 1,
    acaoRecomendada: "Suspender a atividade ate elaborar e aprovar a analise de risco.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR33-EC-001",
    nr: "NR-33",
    atividadeRelacionada: "espaco-confinado",
    perguntaChecklist: "Existe PET valida para entrada no espaco confinado?",
    titulo: "PET para espaco confinado",
    descricao: "Entrada em espaco confinado sem permissao de entrada e trabalho.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Crítica",
    prioridadeSugerida: "Crítica",
    prazoSugeridoDias: 1,
    acaoRecomendada: "Bloquear a entrada ate emissao de PET.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR10-ELE-001",
    nr: "NR-10",
    atividadeRelacionada: "eletricidade",
    perguntaChecklist: "O circuito foi desenergizado e bloqueado?",
    titulo: "Aplicacao de LOTO",
    descricao: "Intervencao eletrica sem desenergizacao ou bloqueio.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Crítica",
    prioridadeSugerida: "Crítica",
    prazoSugeridoDias: 1,
    acaoRecomendada: "Reaplicar procedimento LOTO antes de retomar a atividade.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR12-MAQ-001",
    nr: "NR-12",
    atividadeRelacionada: "maquina-sem-protecao",
    perguntaChecklist: "A maquina opera com protecoes instaladas?",
    titulo: "Protecoes de maquina instaladas",
    descricao: "Maquina operando sem protecao adequada.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Crítica",
    prioridadeSugerida: "Crítica",
    prazoSugeridoDias: 1,
    acaoRecomendada: "Interditar a maquina ate regularizacao das protecoes.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR11-MOV-001",
    nr: "NR-11",
    atividadeRelacionada: "movimentacao-de-carga",
    perguntaChecklist: "O operador possui habilitacao vigente?",
    titulo: "Operador habilitado",
    descricao: "Equipamento de movimentacao operado por profissional nao habilitado.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Alta",
    prioridadeSugerida: "Alta",
    prazoSugeridoDias: 3,
    acaoRecomendada: "Afastar operador e regularizar habilitacao.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR20-INF-001",
    nr: "NR-20",
    atividadeRelacionada: "inflamaveis",
    perguntaChecklist: "Existe APP aprovada para atividade com inflamaveis?",
    titulo: "APP para inflamaveis",
    descricao: "Atividade com inflamaveis sem avaliacao previa de perigos.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Crítica",
    prioridadeSugerida: "Crítica",
    prazoSugeridoDias: 1,
    acaoRecomendada: "Bloquear a atividade ate aprovacao da APP.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR26-SIN-001",
    nr: "NR-26",
    atividadeRelacionada: "sinalizacao",
    perguntaChecklist: "A sinalizacao de risco esta visivel e integra?",
    titulo: "Sinalizacao visivel",
    descricao: "Sinalizacao de risco ausente, danificada ou ilegivel.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Média",
    prioridadeSugerida: "Média",
    prazoSugeridoDias: 7,
    acaoRecomendada: "Substituir ou repor sinalizacao conforme padrao.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR17-ERG-001",
    nr: "NR-17",
    atividadeRelacionada: "ergonomia",
    perguntaChecklist: "O posto atende aos parametros ergonomicos basicos?",
    titulo: "Posto ergonomico adequado",
    descricao: "Posto de trabalho fora de parametros ergonomicos.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Média",
    prioridadeSugerida: "Média",
    prazoSugeridoDias: 15,
    acaoRecomendada: "Ajustar posto de trabalho e registrar adequacao.",
    exigeEvidencia: false,
    ativa: true,
  },
  {
    id: "RULE-NR23-EMG-001",
    nr: "NR-23",
    atividadeRelacionada: "emergencia-incendio",
    perguntaChecklist: "Os equipamentos de incendio estao operantes?",
    titulo: "Combate a incendio operante",
    descricao: "Equipamentos de emergencia fora de validade ou indisponiveis.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Alta",
    prioridadeSugerida: "Alta",
    prazoSugeridoDias: 3,
    acaoRecomendada: "Regularizar equipamentos e desobstruir acesso.",
    exigeEvidencia: true,
    ativa: true,
  },
  {
    id: "RULE-NR18-CC-001",
    nr: "NR-18",
    atividadeRelacionada: "construcao-civil",
    perguntaChecklist: "A area possui protecao coletiva contra quedas?",
    titulo: "Protecao coletiva na construcao",
    descricao: "Area de obra sem protecao coletiva adequada.",
    condicaoDisparo: "ANSWER_NEGATIVE",
    severidadePadrao: "Crítica",
    prioridadeSugerida: "Crítica",
    prazoSugeridoDias: 1,
    acaoRecomendada: "Instalar protecao coletiva e isolar a area.",
    exigeEvidencia: true,
    ativa: true,
  },
];

export const NR_RULES_BY_ID = NR_RULES.reduce((accumulator, rule) => {
  accumulator[rule.id] = rule;
  return accumulator;
}, {});

export function listRulesByActivity(activityType) {
  return NR_RULES.filter((rule) => rule.ativa && rule.atividadeRelacionada === activityType);
}

export function listRulesByNR(nr) {
  return NR_RULES.filter((rule) => rule.ativa && rule.nr === nr);
}

export function getRuleById(ruleId) {
  return NR_RULES_BY_ID[ruleId];
}
