import type { EvidenceKind } from './evidence';
import type { ComplianceStatus } from './compliance';
import type { SSTRuleSeverity, SSTRuleScope } from './sstRule';

export type OperationalItemId = string;

export type OperationalItemKind =
  | 'observation'
  | 'nonconformity'
  | 'incidentSignal'
  | 'regulatoryGap'
  | 'criticalDeviation'
  | 'improvement';

export type OperationalItemPriority = 'baixa' | 'media' | 'alta' | 'critica';

export type OperationalItemStatus =
  | 'draft'
  | 'triaged'
  | 'a_fazer'
  | 'ready'
  | 'inProgress'
  | 'awaitingEvidence'
  | 'em_validacao'
  | 'vencido'
  | 'completed'
  | 'cancelled';

export type OperationalItemSourceType =
  | 'fieldInput'
  | 'inspection'
  | 'checklist'
  | 'manual'
  | 'rule'
  | 'legacy';

export interface OperationalItemSourceLink {
  type: OperationalItemSourceType;
  id: string;
  label?: string;
  questionId?: string;
  ruleId?: string;
}

export interface OperationalItemRuleLink {
  ruleId: string;
  title: string;
  scope: SSTRuleScope;
  severity: SSTRuleSeverity;
  matchedBy?: 'explicit' | 'keyword' | 'context' | 'activity' | 'nr' | 'universal';
  blocking?: boolean;
}

export interface OperationalItemEvidencePlan {
  required: boolean;
  minimumCount: number;
  acceptedKinds: EvidenceKind[];
  blockingForCompletion: boolean;
  rationale: string[];
}

export interface OperationalItemStatusChange {
  fromStatus?: OperationalItemStatus;
  toStatus: OperationalItemStatus;
  changedAt: string;
  changedBy?: string;
  note?: string;
}

export interface OperationalItemLegacyReference {
  model: 'inspection-risk-action';
  inspectionId?: string;
  riskId?: string;
  actionId?: string;
}

export interface OperationalItem {
  id: OperationalItemId;
  title: string;
  description?: string;
  kind: OperationalItemKind;
  priority: OperationalItemPriority;
  status: OperationalItemStatus;
  sector?: string;
  contextId?: string;
  activityId?: string;
  checklistId?: string;
  inspectionId?: string;
  fieldInputId?: string;
  nrIds: string[];
  primaryNr?: string;
  primaryRuleId?: string;
  sourceLinks: OperationalItemSourceLink[];
  ruleLinks: OperationalItemRuleLink[];
  blocking: boolean;
  responsible?: string;
  responsibleRole?: string;
  dueAt?: string;
  evidencePlan: OperationalItemEvidencePlan;
  evidenceRequired?: boolean;
  evidenceIds: string[];
  complianceStatus?: ComplianceStatus;
  auditTrailIds?: string[];
  requiredDocuments?: string[];
  recommendedActions?: string[];
  tags?: string[];
  detectedKeywords?: string[];
  autoGenerated?: boolean;
  legacyReferences?: OperationalItemLegacyReference[];
  history: OperationalItemStatusChange[];
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
}

export interface OperationalItemDraft
  extends Omit<OperationalItem, 'id' | 'history' | 'createdAt' | 'updatedAt'> {
  id?: string;
  history?: OperationalItemStatusChange[];
  createdAt?: string;
  updatedAt?: string;
}

export interface OperationalItemPatch extends Partial<OperationalItemDraft> {
  id: OperationalItemId;
}
